// Modèles locaux de prestations par métier (V1) : aident l'artisan à
// démarrer sa Bibliothèque de prestations sans saisie manuelle longue.
// Aucun appel externe — tout est défini ici, à ajuster ensuite librement par
// l'artisan une fois importé (les fiches importées restent des prestations
// normales, modifiables/désactivables comme les autres).

export interface ServiceProfileTemplate {
  name: string
  category: string
  description: string
  detectionKeywords: string[]
  qualificationQuestions: string[]
  requiredInformation: string[]
  requiredPhotos: boolean
  recommendedQuoteLines: Array<{ label: string; unitPriceHT: number | null; vatRate: number | null }>
  averageDurationMinutes: number | null
  defaultVatRate: number | null
  travelRequired: boolean
  appointmentRecommended: boolean
  emergencySupported: boolean
  relatedServices: string[]
  internalNotes: string
}

export interface ServiceProfileTradeTemplates {
  value: string
  label: string
  templates: ServiceProfileTemplate[]
}

export const SERVICE_PROFILE_TRADES: Array<{ value: string; label: string }> = [
  { value: 'plomberie', label: 'Plomberie' },
  { value: 'electricite', label: 'Électricité' },
  { value: 'chauffage', label: 'Chauffage / climatisation' },
  { value: 'menuiserie', label: 'Menuiserie' },
  { value: 'peinture', label: 'Peinture / rénovation' },
]

export const SERVICE_PROFILE_TEMPLATES: Record<string, ServiceProfileTemplate[]> = {
  plomberie: [
    {
      name: 'Recherche de fuite',
      category: 'Plomberie',
      description: 'Diagnostic et localisation d’une fuite d’eau avant intervention.',
      detectionKeywords: ['fuite', 'infiltration', 'dégât des eaux', 'humidité'],
      qualificationQuestions: ['Où la fuite est-elle visible ?', 'Depuis combien de temps ?', 'L’eau est-elle coupée ?'],
      requiredInformation: ['Localisation précise', 'Accessibilité de la zone'],
      requiredPhotos: true,
      recommendedQuoteLines: [
        { label: 'Recherche de fuite', unitPriceHT: null, vatRate: null },
        { label: 'Déplacement', unitPriceHT: null, vatRate: null },
      ],
      averageDurationMinutes: 90,
      defaultVatRate: 10,
      travelRequired: true,
      appointmentRecommended: false,
      emergencySupported: true,
      relatedServices: ['Réparation évacuation'],
      internalNotes: '',
    },
    {
      name: 'Remplacement chauffe-eau',
      category: 'Plomberie',
      description: 'Dépose de l’ancien chauffe-eau et installation d’un nouveau modèle.',
      detectionKeywords: ['chauffe-eau', 'ballon eau chaude', 'cumulus'],
      qualificationQuestions: ['Quel volume actuel ?', 'Électrique ou thermodynamique ?', 'Accès au local technique ?'],
      requiredInformation: ['Volume souhaité', 'Type d’énergie'],
      requiredPhotos: true,
      recommendedQuoteLines: [
        { label: 'Dépose ancien chauffe-eau', unitPriceHT: null, vatRate: null },
        { label: 'Fourniture / pose chauffe-eau', unitPriceHT: null, vatRate: null },
        { label: 'Mise en service', unitPriceHT: null, vatRate: null },
      ],
      averageDurationMinutes: 150,
      defaultVatRate: 10,
      travelRequired: true,
      appointmentRecommended: true,
      emergencySupported: false,
      relatedServices: [],
      internalNotes: '',
    },
    {
      name: 'Débouchage',
      category: 'Plomberie',
      description: 'Débouchage de canalisation (évier, douche, WC).',
      detectionKeywords: ['bouché', 'débouchage', 'canalisation', 'évacuation lente'],
      qualificationQuestions: ['Quel équipement est concerné ?', 'L’eau s’évacue-t-elle un peu ?'],
      requiredInformation: ['Équipement concerné'],
      requiredPhotos: false,
      recommendedQuoteLines: [
        { label: 'Débouchage', unitPriceHT: null, vatRate: null },
      ],
      averageDurationMinutes: 60,
      defaultVatRate: 10,
      travelRequired: true,
      appointmentRecommended: false,
      emergencySupported: true,
      relatedServices: ['Recherche de fuite'],
      internalNotes: '',
    },
    {
      name: 'Remplacement robinetterie',
      category: 'Plomberie',
      description: 'Dépose et remplacement d’un robinet ou mitigeur.',
      detectionKeywords: ['robinet', 'mitigeur', 'robinetterie'],
      qualificationQuestions: ['Quel type de robinetterie ?', 'Le nouveau matériel est-il déjà acheté ?'],
      requiredInformation: ['Type d’équipement', 'Marque souhaitée'],
      requiredPhotos: true,
      recommendedQuoteLines: [
        { label: 'Dépose ancienne robinetterie', unitPriceHT: null, vatRate: null },
        { label: 'Fourniture / pose robinetterie', unitPriceHT: null, vatRate: null },
      ],
      averageDurationMinutes: 60,
      defaultVatRate: 10,
      travelRequired: true,
      appointmentRecommended: false,
      emergencySupported: false,
      relatedServices: [],
      internalNotes: '',
    },
    {
      name: 'Installation WC',
      category: 'Plomberie',
      description: 'Installation ou remplacement d’un WC.',
      detectionKeywords: ['wc', 'toilettes', 'sanibroyeur'],
      qualificationQuestions: ['WC suspendu ou au sol ?', 'Le modèle est-il déjà choisi ?'],
      requiredInformation: ['Type de WC', 'Configuration de l’évacuation'],
      requiredPhotos: true,
      recommendedQuoteLines: [
        { label: 'Dépose ancien WC', unitPriceHT: null, vatRate: null },
        { label: 'Fourniture / pose WC', unitPriceHT: null, vatRate: null },
      ],
      averageDurationMinutes: 120,
      defaultVatRate: 10,
      travelRequired: true,
      appointmentRecommended: true,
      emergencySupported: false,
      relatedServices: [],
      internalNotes: '',
    },
    {
      name: 'Réparation évacuation',
      category: 'Plomberie',
      description: 'Réparation d’une canalisation ou évacuation endommagée.',
      detectionKeywords: ['évacuation', 'canalisation cassée', 'odeur égout'],
      qualificationQuestions: ['Où se situe l’évacuation concernée ?', 'Le problème est-il récurrent ?'],
      requiredInformation: ['Localisation de l’évacuation'],
      requiredPhotos: true,
      recommendedQuoteLines: [
        { label: 'Diagnostic évacuation', unitPriceHT: null, vatRate: null },
        { label: 'Réparation évacuation', unitPriceHT: null, vatRate: null },
      ],
      averageDurationMinutes: 90,
      defaultVatRate: 10,
      travelRequired: true,
      appointmentRecommended: false,
      emergencySupported: true,
      relatedServices: ['Débouchage'],
      internalNotes: '',
    },
  ],
  electricite: [
    {
      name: 'Mise aux normes tableau électrique',
      category: 'Électricité',
      description: 'Diagnostic et mise en sécurité du tableau électrique.',
      detectionKeywords: ['tableau électrique', 'mise aux normes', 'disjoncteur'],
      qualificationQuestions: ['Le tableau est-il encore aux normes ?', 'Y a-t-il des coupures fréquentes ?'],
      requiredInformation: ['Âge approximatif de l’installation'],
      requiredPhotos: true,
      recommendedQuoteLines: [
        { label: 'Diagnostic électrique', unitPriceHT: null, vatRate: null },
        { label: 'Tableau électrique', unitPriceHT: null, vatRate: null },
        { label: 'Mise en sécurité', unitPriceHT: null, vatRate: null },
      ],
      averageDurationMinutes: 180,
      defaultVatRate: 10,
      travelRequired: true,
      appointmentRecommended: true,
      emergencySupported: false,
      relatedServices: [],
      internalNotes: '',
    },
    {
      name: 'Panne électrique',
      category: 'Électricité',
      description: 'Diagnostic et réparation d’une panne électrique.',
      detectionKeywords: ['panne électrique', 'plus de courant', 'court-circuit', 'disjoncteur saute'],
      qualificationQuestions: ['Toute l’installation est-elle touchée ?', 'Depuis quand ?'],
      requiredInformation: ['Zone concernée par la panne'],
      requiredPhotos: false,
      recommendedQuoteLines: [
        { label: 'Diagnostic panne', unitPriceHT: null, vatRate: null },
        { label: 'Réparation', unitPriceHT: null, vatRate: null },
      ],
      averageDurationMinutes: 90,
      defaultVatRate: 10,
      travelRequired: true,
      appointmentRecommended: false,
      emergencySupported: true,
      relatedServices: [],
      internalNotes: '',
    },
    {
      name: 'Installation prise / interrupteur',
      category: 'Électricité',
      description: 'Ajout ou remplacement d’une prise ou d’un interrupteur.',
      detectionKeywords: ['prise électrique', 'interrupteur', 'prise murale'],
      qualificationQuestions: ['Combien de prises/interrupteurs ?', 'Création ou remplacement ?'],
      requiredInformation: ['Nombre d’éléments', 'Emplacement souhaité'],
      requiredPhotos: false,
      recommendedQuoteLines: [
        { label: 'Installation prise/interrupteur', unitPriceHT: null, vatRate: null },
      ],
      averageDurationMinutes: 45,
      defaultVatRate: 10,
      travelRequired: true,
      appointmentRecommended: false,
      emergencySupported: false,
      relatedServices: [],
      internalNotes: '',
    },
    {
      name: 'Installation luminaire',
      category: 'Électricité',
      description: 'Pose ou remplacement d’un luminaire.',
      detectionKeywords: ['luminaire', 'spot', 'plafonnier', 'éclairage'],
      qualificationQuestions: ['Le luminaire est-il déjà acheté ?', 'Type de plafond ?'],
      requiredInformation: ['Type de luminaire', 'Emplacement'],
      requiredPhotos: true,
      recommendedQuoteLines: [
        { label: 'Installation luminaire', unitPriceHT: null, vatRate: null },
      ],
      averageDurationMinutes: 45,
      defaultVatRate: 10,
      travelRequired: true,
      appointmentRecommended: false,
      emergencySupported: false,
      relatedServices: [],
      internalNotes: '',
    },
    {
      name: 'Mise en conformité électrique',
      category: 'Électricité',
      description: 'Mise en conformité d’une installation électrique existante.',
      detectionKeywords: ['conformité électrique', 'diagnostic électrique', 'norme nfc'],
      qualificationQuestions: ['Avez-vous un diagnostic récent ?', 'Quelle surface concernée ?'],
      requiredInformation: ['Surface du logement', 'Date de l’installation'],
      requiredPhotos: true,
      recommendedQuoteLines: [
        { label: 'Diagnostic conformité', unitPriceHT: null, vatRate: null },
        { label: 'Travaux de mise en conformité', unitPriceHT: null, vatRate: null },
      ],
      averageDurationMinutes: 240,
      defaultVatRate: 10,
      travelRequired: true,
      appointmentRecommended: true,
      emergencySupported: false,
      relatedServices: ['Mise aux normes tableau électrique'],
      internalNotes: '',
    },
  ],
  chauffage: [
    {
      name: 'Entretien chaudière',
      category: 'Chauffage',
      description: 'Entretien annuel obligatoire d’une chaudière.',
      detectionKeywords: ['chaudière', 'entretien chaudière', 'révision chaudière'],
      qualificationQuestions: ['Quel type de chaudière ?', 'Date du dernier entretien ?'],
      requiredInformation: ['Type de chaudière', 'Date dernier entretien'],
      requiredPhotos: false,
      recommendedQuoteLines: [
        { label: 'Entretien chaudière', unitPriceHT: null, vatRate: null },
      ],
      averageDurationMinutes: 60,
      defaultVatRate: 10,
      travelRequired: true,
      appointmentRecommended: true,
      emergencySupported: false,
      relatedServices: [],
      internalNotes: '',
    },
    {
      name: 'Entretien pompe à chaleur',
      category: 'Chauffage',
      description: 'Entretien et contrôle de fonctionnement d’une pompe à chaleur.',
      detectionKeywords: ['pompe à chaleur', 'pac', 'climatisation'],
      qualificationQuestions: ['Quel modèle de PAC ?', 'Constatez-vous une baisse de performance ?'],
      requiredInformation: ['Modèle de la PAC'],
      requiredPhotos: false,
      recommendedQuoteLines: [
        { label: 'Contrôle fonctionnement', unitPriceHT: null, vatRate: null },
        { label: 'Nettoyage filtres', unitPriceHT: null, vatRate: null },
      ],
      averageDurationMinutes: 75,
      defaultVatRate: 10,
      travelRequired: true,
      appointmentRecommended: true,
      emergencySupported: false,
      relatedServices: [],
      internalNotes: '',
    },
    {
      name: 'Panne de chauffage',
      category: 'Chauffage',
      description: 'Diagnostic et dépannage d’une panne de chauffage.',
      detectionKeywords: ['plus de chauffage', 'panne chaudière', 'radiateur froid'],
      qualificationQuestions: ['Tous les radiateurs sont-ils concernés ?', 'Depuis quand ?'],
      requiredInformation: ['Zone affectée'],
      requiredPhotos: false,
      recommendedQuoteLines: [
        { label: 'Diagnostic panne', unitPriceHT: null, vatRate: null },
        { label: 'Réparation', unitPriceHT: null, vatRate: null },
      ],
      averageDurationMinutes: 90,
      defaultVatRate: 10,
      travelRequired: true,
      appointmentRecommended: false,
      emergencySupported: true,
      relatedServices: ['Entretien chaudière'],
      internalNotes: '',
    },
    {
      name: 'Installation climatisation',
      category: 'Climatisation',
      description: 'Installation d’un système de climatisation.',
      detectionKeywords: ['climatisation', 'climatiseur', 'split'],
      qualificationQuestions: ['Combien de pièces à climatiser ?', 'Mono-split ou multi-split ?'],
      requiredInformation: ['Surface à climatiser', 'Nombre de pièces'],
      requiredPhotos: true,
      recommendedQuoteLines: [
        { label: 'Fourniture / pose climatisation', unitPriceHT: null, vatRate: null },
        { label: 'Mise en service', unitPriceHT: null, vatRate: null },
      ],
      averageDurationMinutes: 240,
      defaultVatRate: 10,
      travelRequired: true,
      appointmentRecommended: true,
      emergencySupported: false,
      relatedServices: [],
      internalNotes: '',
    },
    {
      name: 'Purge / équilibrage radiateurs',
      category: 'Chauffage',
      description: 'Purge et équilibrage du circuit de chauffage.',
      detectionKeywords: ['radiateur froid en haut', 'bruit radiateur', 'purge radiateur'],
      qualificationQuestions: ['Quels radiateurs sont concernés ?'],
      requiredInformation: ['Radiateurs concernés'],
      requiredPhotos: false,
      recommendedQuoteLines: [
        { label: 'Purge radiateurs', unitPriceHT: null, vatRate: null },
      ],
      averageDurationMinutes: 60,
      defaultVatRate: 10,
      travelRequired: true,
      appointmentRecommended: false,
      emergencySupported: false,
      relatedServices: [],
      internalNotes: '',
    },
  ],
  menuiserie: [
    {
      name: 'Remplacement fenêtre',
      category: 'Menuiserie',
      description: 'Dépose et remplacement d’une fenêtre.',
      detectionKeywords: ['fenêtre', 'double vitrage', 'remplacement fenêtre'],
      qualificationQuestions: ['Quelles dimensions ?', 'Bois, PVC ou aluminium ?'],
      requiredInformation: ['Dimensions', 'Matériau souhaité'],
      requiredPhotos: true,
      recommendedQuoteLines: [
        { label: 'Dépose ancienne fenêtre', unitPriceHT: null, vatRate: null },
        { label: 'Fourniture / pose fenêtre', unitPriceHT: null, vatRate: null },
      ],
      averageDurationMinutes: 180,
      defaultVatRate: 10,
      travelRequired: true,
      appointmentRecommended: true,
      emergencySupported: false,
      relatedServices: [],
      internalNotes: '',
    },
    {
      name: 'Installation porte intérieure',
      category: 'Menuiserie',
      description: 'Pose ou remplacement d’une porte intérieure.',
      detectionKeywords: ['porte intérieure', 'porte de chambre', 'bloc-porte'],
      qualificationQuestions: ['La porte est-elle déjà achetée ?', 'Quelles dimensions ?'],
      requiredInformation: ['Dimensions de l’ouverture'],
      requiredPhotos: true,
      recommendedQuoteLines: [
        { label: 'Pose porte intérieure', unitPriceHT: null, vatRate: null },
      ],
      averageDurationMinutes: 120,
      defaultVatRate: 10,
      travelRequired: true,
      appointmentRecommended: false,
      emergencySupported: false,
      relatedServices: [],
      internalNotes: '',
    },
    {
      name: 'Remplacement porte d’entrée',
      category: 'Menuiserie',
      description: 'Dépose et remplacement d’une porte d’entrée.',
      detectionKeywords: ['porte d’entrée', 'porte blindée', 'serrure porte entrée'],
      qualificationQuestions: ['Quelles dimensions ?', 'Souhaitez-vous une porte sécurisée ?'],
      requiredInformation: ['Dimensions', 'Niveau de sécurité souhaité'],
      requiredPhotos: true,
      recommendedQuoteLines: [
        { label: 'Dépose ancienne porte', unitPriceHT: null, vatRate: null },
        { label: 'Fourniture / pose porte d’entrée', unitPriceHT: null, vatRate: null },
      ],
      averageDurationMinutes: 180,
      defaultVatRate: 10,
      travelRequired: true,
      appointmentRecommended: true,
      emergencySupported: false,
      relatedServices: [],
      internalNotes: '',
    },
    {
      name: 'Pose de placards / dressing',
      category: 'Menuiserie',
      description: 'Conception et installation de placards ou dressing sur mesure.',
      detectionKeywords: ['placard', 'dressing', 'rangement sur mesure'],
      qualificationQuestions: ['Quelle surface disponible ?', 'Sur mesure ou standard ?'],
      requiredInformation: ['Dimensions disponibles'],
      requiredPhotos: true,
      recommendedQuoteLines: [
        { label: 'Fourniture / pose placard', unitPriceHT: null, vatRate: null },
      ],
      averageDurationMinutes: 240,
      defaultVatRate: 10,
      travelRequired: true,
      appointmentRecommended: true,
      emergencySupported: false,
      relatedServices: [],
      internalNotes: '',
    },
    {
      name: 'Réparation volet',
      category: 'Menuiserie',
      description: 'Réparation d’un volet roulant ou battant.',
      detectionKeywords: ['volet', 'volet roulant bloqué', 'volet cassé'],
      qualificationQuestions: ['Volet roulant ou battant ?', 'Quel est le problème constaté ?'],
      requiredInformation: ['Type de volet'],
      requiredPhotos: true,
      recommendedQuoteLines: [
        { label: 'Diagnostic volet', unitPriceHT: null, vatRate: null },
        { label: 'Réparation volet', unitPriceHT: null, vatRate: null },
      ],
      averageDurationMinutes: 90,
      defaultVatRate: 10,
      travelRequired: true,
      appointmentRecommended: false,
      emergencySupported: false,
      relatedServices: [],
      internalNotes: '',
    },
  ],
  peinture: [
    {
      name: 'Peinture intérieure',
      category: 'Peinture',
      description: 'Travaux de peinture pour une ou plusieurs pièces.',
      detectionKeywords: ['peinture', 'repeindre', 'mur à peindre'],
      qualificationQuestions: ['Combien de pièces / m² ?', 'État actuel des murs ?'],
      requiredInformation: ['Surface à peindre', 'État des murs'],
      requiredPhotos: true,
      recommendedQuoteLines: [
        { label: 'Préparation des surfaces', unitPriceHT: null, vatRate: null },
        { label: 'Peinture', unitPriceHT: null, vatRate: null },
      ],
      averageDurationMinutes: 240,
      defaultVatRate: 10,
      travelRequired: true,
      appointmentRecommended: true,
      emergencySupported: false,
      relatedServices: [],
      internalNotes: '',
    },
    {
      name: 'Ravalement de façade',
      category: 'Rénovation',
      description: 'Rénovation et traitement de la façade extérieure.',
      detectionKeywords: ['ravalement', 'façade', 'enduit façade'],
      qualificationQuestions: ['Quelle surface de façade ?', 'État actuel de la façade ?'],
      requiredInformation: ['Surface de façade', 'Hauteur du bâtiment'],
      requiredPhotos: true,
      recommendedQuoteLines: [
        { label: 'Diagnostic façade', unitPriceHT: null, vatRate: null },
        { label: 'Ravalement de façade', unitPriceHT: null, vatRate: null },
      ],
      averageDurationMinutes: 480,
      defaultVatRate: 10,
      travelRequired: true,
      appointmentRecommended: true,
      emergencySupported: false,
      relatedServices: [],
      internalNotes: '',
    },
    {
      name: 'Pose de revêtement de sol',
      category: 'Rénovation',
      description: 'Pose de carrelage, parquet ou autre revêtement de sol.',
      detectionKeywords: ['revêtement de sol', 'carrelage', 'parquet'],
      qualificationQuestions: ['Quel type de revêtement souhaité ?', 'Quelle surface ?'],
      requiredInformation: ['Surface à couvrir', 'Type de revêtement'],
      requiredPhotos: true,
      recommendedQuoteLines: [
        { label: 'Préparation du sol', unitPriceHT: null, vatRate: null },
        { label: 'Pose du revêtement', unitPriceHT: null, vatRate: null },
      ],
      averageDurationMinutes: 360,
      defaultVatRate: 10,
      travelRequired: true,
      appointmentRecommended: true,
      emergencySupported: false,
      relatedServices: [],
      internalNotes: '',
    },
    {
      name: 'Pose de papier peint',
      category: 'Peinture',
      description: 'Pose de papier peint sur un ou plusieurs murs.',
      detectionKeywords: ['papier peint', 'tapisserie'],
      qualificationQuestions: ['Quelle surface concernée ?', 'Le papier peint est-il déjà choisi ?'],
      requiredInformation: ['Surface concernée'],
      requiredPhotos: true,
      recommendedQuoteLines: [
        { label: 'Préparation des murs', unitPriceHT: null, vatRate: null },
        { label: 'Pose papier peint', unitPriceHT: null, vatRate: null },
      ],
      averageDurationMinutes: 180,
      defaultVatRate: 10,
      travelRequired: true,
      appointmentRecommended: true,
      emergencySupported: false,
      relatedServices: [],
      internalNotes: '',
    },
    {
      name: 'Rénovation complète de pièce',
      category: 'Rénovation',
      description: 'Rénovation globale d’une pièce (peinture, sol, finitions).',
      detectionKeywords: ['rénovation complète', 'rénover une pièce', 'remise à neuf'],
      qualificationQuestions: ['Quelle pièce ?', 'Quelle surface ?', 'Quel budget envisagé ?'],
      requiredInformation: ['Pièce concernée', 'Surface', 'Budget envisagé'],
      requiredPhotos: true,
      recommendedQuoteLines: [
        { label: 'Diagnostic rénovation', unitPriceHT: null, vatRate: null },
        { label: 'Travaux de rénovation', unitPriceHT: null, vatRate: null },
      ],
      averageDurationMinutes: 600,
      defaultVatRate: 10,
      travelRequired: true,
      appointmentRecommended: true,
      emergencySupported: false,
      relatedServices: [],
      internalNotes: '',
    },
  ],
}

/**
 * Transforme un modèle local en payload prêt à être envoyé à
 * POST /api/artisan/service-profiles (mêmes clés que buildServiceProfilePayload
 * côté page Profil métier).
 */
export function serviceProfileTemplateToPayload(template: ServiceProfileTemplate): Record<string, unknown> {
  return {
    name: template.name,
    category: template.category || null,
    description: template.description || null,
    isActive: true,
    detectionKeywords: template.detectionKeywords,
    qualificationQuestions: template.qualificationQuestions,
    requiredInformation: template.requiredInformation,
    requiredPhotos: template.requiredPhotos,
    recommendedQuoteLines: template.recommendedQuoteLines,
    averageDurationMinutes: template.averageDurationMinutes,
    defaultVatRate: template.defaultVatRate,
    travelRequired: template.travelRequired,
    appointmentRecommended: template.appointmentRecommended,
    emergencySupported: template.emergencySupported,
    relatedServices: template.relatedServices,
    internalNotes: template.internalNotes || null,
  }
}
