'use client'

import { useEffect, useState } from 'react'
import { ARTISAN_TRADES } from '@/src/config/trades'
import { hasPermission } from '@/src/lib/team/permission-matrix'
import { ReadOnlyNotice } from '@/src/components/settings/ReadOnlyNotice'
import { SettingsPanel } from '@/src/components/settings/SettingsPanel'
import { useActivitySettingsData, type BusinessProfile, type TravelSettings } from '@/src/hooks/useActivitySettingsData'

const input = 'mt-1 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm text-slate-900 outline-none focus:border-emerald-500 focus:ring-2 focus:ring-emerald-100 disabled:bg-slate-50'
const split = (value: string) => value.split(',').map(item => item.trim()).filter(Boolean)

function Save({ onClick, saving, message, disabled }: { onClick: () => void; saving: boolean; message?: string; disabled?: boolean }) { return <div className="mt-4 flex items-center gap-3"><button type="button" disabled={saving || disabled} onClick={onClick} className="rounded-lg bg-emerald-600 px-4 py-2 text-sm font-medium text-white hover:bg-emerald-700 disabled:opacity-60">{saving ? 'Sauvegarde…' : 'Enregistrer'}</button>{message && <p className={message === 'Enregistré' || message.includes('enregistré') || message.includes('jour') ? 'text-sm text-emerald-700' : 'text-sm text-red-600'}>{message}</p>}</div> }
export function ActivitySettingsView() { const activity = useActivitySettingsData(); const [profile, setProfile] = useState<BusinessProfile>(activity.profile); const [travel, setTravel] = useState<TravelSettings>(activity.travel); useEffect(() => { if (!activity.loading) { const timer = window.setTimeout(() => { setProfile(activity.profile); setTravel(activity.travel) }, 0); return () => window.clearTimeout(timer) } }, [activity.loading, activity.profile, activity.travel]); const canEdit = hasPermission(activity.role ?? 'viewer', 'business_settings.update'); const update = <K extends keyof BusinessProfile>(key: K, value: BusinessProfile[K]) => setProfile(current => ({ ...current, [key]: value })); const updateTravel = <K extends keyof TravelSettings>(key: K, value: TravelSettings[K]) => setTravel(current => ({ ...current, [key]: value })); if (activity.loading) return <div className="rounded-xl border border-slate-200 bg-white p-5 text-sm text-slate-600">Chargement de l’activité…</div>; if (activity.error) return <p role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{activity.error}</p>; const readOnly = !canEdit
  return <div className="space-y-4">{readOnly && <ReadOnlyNotice message="Les réglages d’activité sont en lecture seule pour votre rôle." />}
    <SettingsPanel title="Métier et prestations" description="Ces informations aident Kadria à reconnaître les demandes adaptées à votre entreprise." status={profile.primaryTrade ? 'complete' : 'incomplete'}><div className="grid gap-4 md:grid-cols-2"><label className="text-sm font-medium text-slate-700">Métier principal<select className={input} disabled={readOnly} value={profile.primaryTrade} onChange={e => update('primaryTrade', e.target.value)}><option value="">Sélectionner</option>{ARTISAN_TRADES.map(trade => <option key={trade.value} value={trade.value}>{trade.label}</option>)}</select></label><label className="text-sm font-medium text-slate-700">Métiers couverts<input className={input} disabled={readOnly} value={profile.coveredTrades.join(', ')} onChange={e => update('coveredTrades', split(e.target.value))} /></label><label className="text-sm font-medium text-slate-700">Spécialités / travaux acceptés<input className={input} disabled={readOnly} value={profile.specialties.join(', ')} onChange={e => update('specialties', split(e.target.value))} /></label><label className="text-sm font-medium text-slate-700">Travaux refusés<input className={input} disabled={readOnly} value={profile.excludedServices.join(', ')} onChange={e => update('excludedServices', split(e.target.value))} /></label></div><div className="mt-5 border-t border-slate-100 pt-4"><p className="text-sm font-medium text-slate-800">Catalogue de prestations</p>{activity.catalog.length ? <div className="mt-2 divide-y divide-slate-100">{activity.catalog.map(item => <div key={item.id} className="flex items-center justify-between gap-3 py-2"><span className="text-sm text-slate-700">{item.name}</span><button type="button" disabled={readOnly} onClick={() => void activity.toggleCatalog(item)} className="rounded-md border border-slate-300 px-3 py-1 text-xs font-medium text-slate-700 disabled:opacity-60">{item.is_active ? 'Désactiver' : 'Activer'}</button></div>)}</div> : <p className="mt-2 text-sm text-slate-500">Aucune prestation à configurer.</p>}</div><Save disabled={readOnly} saving={activity.status.trade === 'saving'} message={activity.messages.trade} onClick={() => void activity.saveProfile('trade', { primaryTrade: profile.primaryTrade, coveredTrades: profile.coveredTrades, specialties: profile.specialties, excludedServices: profile.excludedServices })} /></SettingsPanel>
    <SettingsPanel title="Qualification des demandes" description="Kadria utilise ces règles pour poser les bonnes questions et préparer des dossiers exploitables." status={activity.derived.activeServiceProfiles.length ? 'complete' : 'incomplete'}>{activity.serviceProfiles.length ? <div className="divide-y divide-slate-100">{activity.serviceProfiles.map(item => <div key={item.id} className="flex items-center justify-between gap-4 py-3"><div><p className="text-sm font-medium text-slate-800">{item.name}</p><p className="text-xs text-slate-500">{item.qualification_questions.length} question(s) · {item.is_active ? 'Actif' : 'Inactif'}</p></div><button type="button" disabled={readOnly} onClick={() => void activity.toggleServiceProfile(item)} className="rounded-md border border-slate-300 px-3 py-1.5 text-xs font-medium text-slate-700 disabled:opacity-60">{item.is_active ? 'Désactiver' : 'Activer'}</button></div>)}</div> : <p className="text-sm text-slate-500">Aucun profil de qualification disponible.</p>}<p className="mt-3 text-sm text-slate-500">Les profils sont activables ici ; leur contenu n’est pas modifié dans cette page.</p>{activity.messages.qualification && <p className="mt-2 text-sm text-slate-600">{activity.messages.qualification}</p>}</SettingsPanel>
    <SettingsPanel title="Zone et déplacements" description="Kadria utilise ces informations pour évaluer la faisabilité et le coût des déplacements." status={profile.baseCity && profile.interventionRadiusKm ? 'complete' : 'incomplete'}><div className="grid gap-4 md:grid-cols-2"><label className="text-sm font-medium text-slate-700">Point de départ<input className={input} disabled={readOnly} value={profile.baseCity} onChange={e => update('baseCity', e.target.value)} /></label><label className="text-sm font-medium text-slate-700">Rayon d’intervention (km)<input className={input} disabled={readOnly} type="number" value={profile.interventionRadiusKm} onChange={e => update('interventionRadiusKm', e.target.value)} /></label><label className="text-sm font-medium text-slate-700">Frais fixes HT (€)<input className={input} disabled={readOnly} type="number" value={profile.travelFeeHt} onChange={e => update('travelFeeHt', e.target.value)} /></label><label className="text-sm font-medium text-slate-700">Frais par km HT (€)<input className={input} disabled={readOnly} type="number" value={profile.travelFeePerKm} onChange={e => update('travelFeePerKm', e.target.value)} /></label><label className="text-sm font-medium text-slate-700">Zone sans frais (km)<input className={input} disabled={readOnly} type="number" value={travel.freeTravelRadiusKm} onChange={e => updateTravel('freeTravelRadiusKm', e.target.value)} /></label></div><p className="mt-3 text-sm text-slate-500">Le véhicule personnel reste géré dans son profil dédié. Les frais internes non consommés ne sont pas exposés ici.</p><Save disabled={readOnly} saving={activity.status.travel === 'saving'} message={activity.messages.travel} onClick={() => void activity.saveTravelDomain({ baseCity: profile.baseCity, interventionRadiusKm: profile.interventionRadiusKm, travelFeeHt: profile.travelFeeHt, travelFeePerKm: profile.travelFeePerKm }, travel, activity.vehicle)} /></SettingsPanel>
  </div>
}
