'use client'

import { useState } from 'react'
import { ARTISAN_TRADES } from '@/src/config/trades'
import { hasPermission } from '@/src/lib/team/permission-matrix'
import { PermissionGate } from '@/src/components/settings/PermissionGate'
import { ReadOnlyNotice } from '@/src/components/settings/ReadOnlyNotice'
import { PERSONAL_VEHICLE_TYPE_LABELS, type PersonalVehicleType } from '@/src/lib/profile/types'
import { useActivitySettingsData, type BusinessProfile, type TravelSettings } from '@/src/hooks/useActivitySettingsData'

type Activity = ReturnType<typeof useActivitySettingsData>
const card = 'rounded-xl border border-slate-200 bg-white p-5 shadow-sm'
const input = 'mt-1 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm text-slate-900 outline-none focus:border-emerald-500 focus:ring-2 focus:ring-emerald-100'
function Feedback({ activity, domain }: { activity: Activity; domain: string }) { const state = activity.status[domain]; const message = activity.messages[domain]; return <p className={`mt-3 text-sm ${state === 'error' ? 'text-red-600' : state === 'saved' ? 'text-emerald-700' : 'text-slate-500'}`}>{state === 'saving' ? 'Sauvegarde en cours…' : message}</p> }
function Save({ activity, domain, onClick, disabled }: { activity: Activity; domain: string; onClick: () => void; disabled?: boolean }) { return <button type="button" onClick={onClick} disabled={disabled || activity.status[domain] === 'saving'} className="mt-4 rounded-lg bg-emerald-600 px-4 py-2 text-sm font-medium text-white hover:bg-emerald-700 disabled:opacity-60">{activity.status[domain] === 'saving' ? 'Sauvegarde…' : activity.status[domain] === 'saved' ? 'Sauvegardé' : 'Enregistrer'}</button> }
function Tags({ values, tone = 'slate' }: { values: string[]; tone?: 'slate' | 'red' }) { return values.length ? <div className="mt-3 flex flex-wrap gap-2">{values.map(value => <span key={value} className={tone === 'red' ? 'rounded-full border border-red-200 bg-red-50 px-2.5 py-1 text-xs text-red-700' : 'rounded-full border border-slate-200 bg-slate-50 px-2.5 py-1 text-xs text-slate-700'}>{value}</span>)}</div> : <p className="mt-3 text-sm text-slate-500">Aucune donnée configurée.</p> }

export function ActivitySettingsView() {
  const activity = useActivitySettingsData()
  return <ActivitySettingsContent activity={activity} />
}

/** Réutilisable par la route legacy une fois son shell historique retiré. */
export function ActivitySettingsContent({ activity }: { activity: Activity }) {
  const canEdit = hasPermission(activity.role ?? 'viewer', 'business_settings.update'); const canVehicle = hasPermission(activity.role ?? 'viewer', 'vehicle.update_self')
  const [draft, setDraft] = useState<BusinessProfile>(activity.profile); const [travelDraft, setTravelDraft] = useState<TravelSettings>(activity.travel); const [unknownTrade, setUnknownTrade] = useState('')
  // Remounting this view after loading keeps local multi-field drafts aligned with the authoritative endpoints.
  if (draft !== activity.profile && activity.status.trade === 'saved') setDraft(activity.profile)
  const update = <K extends keyof BusinessProfile>(key: K, value: BusinessProfile[K]) => setDraft(current => ({ ...current, [key]: value }))
  const updateTravel = <K extends keyof TravelSettings>(key: K, value: TravelSettings[K]) => setTravelDraft(current => ({ ...current, [key]: value }))
  if (activity.loading) return <div className={card}>Chargement de l’activité…</div>
  if (activity.error) return <p role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{activity.error}</p>
  return <div className="space-y-4"><PermissionGate role={activity.role} permission="business_settings.update" fallback={<ReadOnlyNotice message="Les réglages d’activité sont réservés au propriétaire et aux administrateurs." />}><section className={card}><h2 className="text-base font-semibold text-slate-900">Profil métier</h2><p className="mt-1 text-sm text-slate-600">Métier principal et statut de configuration utilisés par Kadria.</p><div className="mt-4 grid gap-4 md:grid-cols-2"><label className="text-sm font-medium text-slate-700">Métier principal<select className={input} value={draft.primaryTrade} onChange={e => update('primaryTrade', e.target.value)}><option value="">Sélectionner</option>{ARTISAN_TRADES.map(trade => <option key={trade.value} value={trade.value}>{trade.label}</option>)}</select></label><div className="text-sm text-slate-600"><span className="font-medium text-slate-700">Statut</span><p className="mt-2">{draft.primaryTrade ? 'Profil configuré' : 'Configuration à compléter'}</p></div></div>{draft.primaryTrade === 'autre' && <div className="mt-4"><label className="text-sm font-medium text-slate-700">Métier personnalisé<input className={input} value={unknownTrade} onChange={e => setUnknownTrade(e.target.value)} /></label><button type="button" onClick={() => activity.reportUnknownTrade(unknownTrade)} className="mt-2 text-sm font-medium text-emerald-700">Signaler ce métier à Kadria</button><Feedback activity={activity} domain="trade" /></div>}<Save activity={activity} domain="profile" onClick={() => activity.saveProfile('profile', { primaryTrade: draft.primaryTrade })} disabled={!canEdit} /><Feedback activity={activity} domain="profile" /></section>
  <section className={card}><h2 className="text-base font-semibold text-slate-900">Métiers couverts</h2><p className="mt-1 text-sm text-slate-600">Les domaines et spécialités réellement couverts par votre activité.</p><label className="mt-4 block text-sm font-medium text-slate-700">Métiers secondaires (séparés par des virgules)<input className={input} value={draft.coveredTrades.join(', ')} onChange={e => update('coveredTrades', e.target.value.split(',').map(v => v.trim()).filter(Boolean))} /></label><label className="mt-4 block text-sm font-medium text-slate-700">Spécialités et travaux acceptés<input className={input} value={draft.specialties.join(', ')} onChange={e => update('specialties', e.target.value.split(',').map(v => v.trim()).filter(Boolean))} /></label><Save activity={activity} domain="covered" onClick={() => activity.saveProfile('covered', { coveredTrades: draft.coveredTrades, specialties: draft.specialties })} /><Feedback activity={activity} domain="covered" /></section>
  <section className={card}><h2 className="text-base font-semibold text-slate-900">Prestations et services</h2><p className="mt-1 text-sm text-slate-600">Catalogue existant : {activity.derived.activeCatalog.length} actif(s), {activity.derived.inactiveCatalog.length} inactif(s).</p><div className="mt-4 divide-y divide-slate-100">{activity.catalog.map(item => <div key={item.id} className="flex items-center justify-between gap-3 py-3"><div><p className="text-sm font-medium text-slate-800">{item.name}</p><p className="text-xs text-slate-500">{item.category || 'Sans catégorie'}{item.price_ht != null ? ` · ${item.price_ht} € HT` : ''}</p></div><button type="button" onClick={() => activity.toggleCatalog(item)} className="rounded-md border border-slate-300 px-3 py-1.5 text-xs font-medium text-slate-700">{item.is_active ? 'Désactiver' : 'Activer'}</button></div>)}</div><Feedback activity={activity} domain="services" /></section>
  <section className={card}><h2 className="text-base font-semibold text-slate-900">Travaux acceptés</h2><p className="mt-1 text-sm text-slate-600">Spécialités incluses dans votre périmètre d’intervention.</p><Tags values={draft.specialties} /></section>
  <section className={card}><h2 className="text-base font-semibold text-slate-900">Travaux refusés</h2><p className="mt-1 text-sm text-slate-600">Exclusions prises en compte dans les demandes.</p><input className={input} value={draft.excludedServices.join(', ')} onChange={e => update('excludedServices', e.target.value.split(',').map(v => v.trim()).filter(Boolean))} placeholder="Ex. dépannage gaz, toiture" /><Tags values={draft.excludedServices} tone="red" /><Save activity={activity} domain="excluded" onClick={() => activity.saveProfile('excluded', { excludedServices: draft.excludedServices })} /><Feedback activity={activity} domain="excluded" /></section>
  <section className={card}><h2 className="text-base font-semibold text-slate-900">Qualification des demandes</h2><p className="mt-1 text-sm text-slate-600">Ces profils guident l’assistant web, l’assistant vocal et la création des dossiers.</p><div className="mt-4 divide-y divide-slate-100">{activity.serviceProfiles.map(item => <div key={item.id} className="flex items-center justify-between gap-3 py-3"><div><p className="text-sm font-medium text-slate-800">{item.name}</p><p className="text-xs text-slate-500">{item.qualification_questions.length} question(s), {item.qualification_fields.length} champ(s) · {item.is_active ? 'Actif' : 'Inactif'}</p></div><button type="button" onClick={() => activity.toggleServiceProfile(item)} className="rounded-md border border-slate-300 px-3 py-1.5 text-xs font-medium text-slate-700">{item.is_active ? 'Désactiver' : 'Activer'}</button></div>)}</div><Feedback activity={activity} domain="qualification" /></section></PermissionGate>
  <section className={card}><h2 className="text-base font-semibold text-slate-900">Déplacements professionnels</h2><p className="mt-1 text-sm text-slate-600">Véhicule personnel, point de départ et règles de frais opérationnels.</p>{!canVehicle && <ReadOnlyNotice message="Le véhicule personnel ne peut être modifié que par son propriétaire." />}<div className="mt-4 grid gap-4 md:grid-cols-2"><label className="text-sm font-medium text-slate-700">Véhicule<select className={input} value={activity.vehicle?.vehicleType || ''} disabled={!canVehicle} onChange={e => activity.setVehicle(activity.vehicle ? { ...activity.vehicle, vehicleType: (e.target.value || null) as PersonalVehicleType | null } : null)}><option value="">Non renseigné</option>{Object.entries(PERSONAL_VEHICLE_TYPE_LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="text-sm font-medium text-slate-700">Point de départ<input className={input} value={draft.baseCity} onChange={e => update('baseCity', e.target.value)} /></label><label className="text-sm font-medium text-slate-700">Rayon d’intervention (km)<input className={input} type="number" value={draft.interventionRadiusKm} onChange={e => update('interventionRadiusKm', e.target.value)} /></label><label className="text-sm font-medium text-slate-700">Frais fixes HT (€)<input className={input} type="number" value={draft.travelFeeHt} onChange={e => update('travelFeeHt', e.target.value)} /></label><label className="text-sm font-medium text-slate-700">Frais par km HT (€)<input className={input} type="number" value={draft.travelFeePerKm} onChange={e => update('travelFeePerKm', e.target.value)} /></label><label className="text-sm font-medium text-slate-700">Zone sans frais (km)<input className={input} type="number" value={travelDraft.freeTravelRadiusKm} onChange={e => updateTravel('freeTravelRadiusKm', e.target.value)} /></label></div><Save activity={activity} domain="travel" disabled={!canEdit} onClick={() => { void activity.saveProfile('travel', { baseCity: draft.baseCity, interventionRadiusKm: draft.interventionRadiusKm, travelFeeHt: draft.travelFeeHt, travelFeePerKm: draft.travelFeePerKm }); void activity.saveTravel(travelDraft, activity.vehicle) }} /><Feedback activity={activity} domain="travel" /></section></div>
}
