'use client'

import { useState } from 'react'
import type { CompanySettingsValues } from '@/src/components/settings/sections/CompanySettingsSection'
import { Card, fieldClassName, SaveButton } from './CompanyFormPrimitives'

export function CompanyLegalCard({ values, onSave, readOnly }: { values: CompanySettingsValues; onSave: (values: CompanySettingsValues) => Promise<void>; readOnly: boolean }) {
  const [local, setLocal] = useState(values), [saving, setSaving] = useState(false), [saved, setSaved] = useState(false), [error, setError] = useState('')
  const save = async () => { if (local.siret && !/^\d{14}$/.test(local.siret)) return setError('Le SIRET doit contenir exactement 14 chiffres.'); setSaving(true); setError(''); try { await onSave(local); setSaved(true); window.setTimeout(() => setSaved(false), 3000) } catch (cause) { setError(cause instanceof Error ? cause.message : 'Enregistrement impossible.') } finally { setSaving(false) } }
  return <Card title="Informations légales et documentaires" description="Ces informations sont utilisées pour identifier votre entreprise dans vos documents."><fieldset disabled={readOnly} className="grid gap-4 md:grid-cols-2"><label className="text-sm font-medium text-slate-700">Raison sociale<input className={fieldClassName} value={local.raisonSociale} onChange={(event) => setLocal({ ...local, raisonSociale: event.target.value })} /></label><label className="text-sm font-medium text-slate-700">Forme juridique<input className={fieldClassName} value={local.formeJuridique} onChange={(event) => setLocal({ ...local, formeJuridique: event.target.value })} /></label><label className="text-sm font-medium text-slate-700">SIRET<input inputMode="numeric" maxLength={14} className={fieldClassName} value={local.siret} onChange={(event) => setLocal({ ...local, siret: event.target.value.replace(/\D/g, '') })} /></label><label className="text-sm font-medium text-slate-700">Numéro de TVA<input className={fieldClassName} value={local.tvaNumber} onChange={(event) => setLocal({ ...local, tvaNumber: event.target.value })} /></label><label className="flex items-center gap-2 text-sm font-medium text-slate-700 md:col-span-2"><input type="checkbox" checked={!local.tvaAssujetti} onChange={(event) => setLocal({ ...local, tvaAssujetti: !event.target.checked })} />Je ne suis pas assujetti à la TVA</label><label className="text-sm font-medium text-slate-700">Assureur<input className={fieldClassName} value={local.assureur} onChange={(event) => setLocal({ ...local, assureur: event.target.value })} /></label><label className="text-sm font-medium text-slate-700">N° de police d’assurance<input className={fieldClassName} value={local.numAssurance} onChange={(event) => setLocal({ ...local, numAssurance: event.target.value })} /></label><label className="flex items-center gap-2 text-sm font-medium text-slate-700 md:col-span-2"><input type="checkbox" checked={local.assuranceNonRequise} onChange={(event) => setLocal({ ...local, assuranceNonRequise: event.target.checked })} />Assurance non requise</label><label className="text-sm font-medium text-slate-700 md:col-span-2">Mention légale personnalisée<textarea className={fieldClassName} rows={3} value={local.devisMentionLegale} onChange={(event) => setLocal({ ...local, devisMentionLegale: event.target.value })} /></label></fieldset>{!readOnly && <div className="mt-5 border-t border-slate-100 pt-4"><SaveButton saving={saving} saved={saved} onClick={save} />{error && <p role="alert" className="mt-2 text-sm text-red-600">{error}</p>}</div>}</Card>
}
