'use client'

import { useState } from 'react'
import Image from 'next/image'
import type { CompanySettingsValues } from '@/src/components/settings/sections/CompanySettingsSection'
import { Card, SaveButton } from './CompanyFormPrimitives'

export function CompanyBrandingCard({ values, uploading, uploadError, onUploadLogo, onRemoveLogo, onSave, readOnly }: { values: CompanySettingsValues; uploading: boolean; uploadError: string | null; onUploadLogo: (file: File) => Promise<void>; onRemoveLogo: () => void; onSave: (values: CompanySettingsValues) => Promise<void>; readOnly: boolean }) {
  const [local, setLocal] = useState(values), [saving, setSaving] = useState(false), [saved, setSaved] = useState(false), [error, setError] = useState('')
  const save = async () => { setSaving(true); setError(''); try { await onSave(local); setSaved(true); window.setTimeout(() => setSaved(false), 3000) } catch (cause) { setError(cause instanceof Error ? cause.message : 'Enregistrement impossible.') } finally { setSaving(false) } }
  return <Card title="Identité visuelle" description="Votre logo est utilisé dans les documents et les espaces où l’identité de votre entreprise est affichée."><fieldset disabled={readOnly}><div className="flex flex-wrap items-center gap-4">{local.logoUrl ? <Image unoptimized src={local.logoUrl} alt="Logo de l’entreprise" width={128} height={64} className="h-16 w-32 rounded-lg border border-slate-200 bg-slate-50 object-contain p-2" onError={(event) => { event.currentTarget.style.display = 'none' }} /> : <div className="flex h-16 w-32 items-center justify-center rounded-lg border border-dashed border-slate-300 text-xs text-slate-500">Aucun logo</div>}<label className="cursor-pointer rounded-lg border border-slate-200 px-4 py-2 text-sm font-medium text-slate-700 transition hover:bg-slate-50">{uploading ? 'Import en cours…' : local.logoUrl ? 'Remplacer le logo' : 'Importer un logo'}<input type="file" className="sr-only" accept="image/png,image/jpeg,image/webp" disabled={uploading} onChange={async (event) => { const file = event.target.files?.[0]; event.target.value = ''; if (!file) return; await onUploadLogo(file) }} /></label>{local.logoUrl && <button type="button" className="text-sm font-medium text-slate-600 hover:text-red-600" onClick={() => { setLocal({ ...local, logoUrl: '' }); onRemoveLogo() }}>Supprimer</button>}</div><p className="mt-3 text-xs text-slate-500">PNG, JPG ou WEBP, 4 Mo maximum.</p>{uploadError && !uploading && <p role="alert" className="mt-2 text-sm text-red-600">{uploadError}</p>}</fieldset>{!readOnly && <div className="mt-5 border-t border-slate-100 pt-4"><SaveButton saving={saving} saved={saved} onClick={save} />{error && <p role="alert" className="mt-2 text-sm text-red-600">{error}</p>}</div>}</Card>
}
