'use client'

import { useState } from 'react'
import type { CompanySettingsValues } from '@/src/components/settings/sections/CompanySettingsSection'
import { Card, fieldClassName, SaveButton } from './CompanyFormPrimitives'

export function CompanyContactCard({ values, onSave, readOnly }: { values: CompanySettingsValues; onSave: (values: CompanySettingsValues) => Promise<void>; readOnly: boolean }) {
  const [local, setLocal] = useState(values), [saving, setSaving] = useState(false), [saved, setSaved] = useState(false), [error, setError] = useState('')
  const save = async () => { setSaving(true); setError(''); try { await onSave(local); setSaved(true); window.setTimeout(() => setSaved(false), 3000) } catch (cause) { setError(cause instanceof Error ? cause.message : 'Enregistrement impossible.') } finally { setSaving(false) } }
  return <Card title="Coordonnées de l’entreprise" description="Utilisées dans vos devis, vos e-mails et lorsque vos coordonnées sont affichées à vos clients."><fieldset disabled={readOnly} className="grid gap-4 md:grid-cols-2"><label className="text-sm font-medium text-slate-700">Téléphone professionnel<input type="tel" className={fieldClassName} value={local.phone} onChange={(event) => setLocal({ ...local, phone: event.target.value })} /></label><label className="text-sm font-medium text-slate-700">E-mail de notification<input type="email" className={fieldClassName} value={local.notificationEmail} onChange={(event) => setLocal({ ...local, notificationEmail: event.target.value })} /></label><label className="text-sm font-medium text-slate-700 md:col-span-2">Adresse<input className={fieldClassName} value={local.adressePro} onChange={(event) => setLocal({ ...local, adressePro: event.target.value })} /></label><label className="text-sm font-medium text-slate-700">Code postal<input className={fieldClassName} value={local.cpPro} onChange={(event) => setLocal({ ...local, cpPro: event.target.value })} /></label><label className="text-sm font-medium text-slate-700">Ville<input className={fieldClassName} value={local.villePro} onChange={(event) => setLocal({ ...local, villePro: event.target.value })} /></label></fieldset>{!readOnly && <div className="mt-5 border-t border-slate-100 pt-4"><SaveButton saving={saving} saved={saved} onClick={save} />{error && <p role="alert" className="mt-2 text-sm text-red-600">{error}</p>}</div>}</Card>
}
