'use client'

import Link from 'next/link'
import { FormEvent, useState } from 'react'
import { TEAM_ROLE_DESCRIPTIONS, TEAM_ROLE_LABELS, type TenantRole } from '@/src/lib/team/types'
import { ReadOnlyNotice } from '@/src/components/settings/ReadOnlyNotice'
import { SettingsPanel } from '@/src/components/settings/SettingsPanel'
import { useTeamSettingsData } from '@/src/hooks/useTeamSettingsData'

const date = (value: string | null) => value ? new Date(value).toLocaleDateString('fr-FR') : 'Non disponible'
const memberName = (member: { firstName: string; lastName: string; email: string }) => [member.firstName, member.lastName].filter(Boolean).join(' ') || member.email

export function TeamSettingsView() {
  const data = useTeamSettingsData(); const [email, setEmail] = useState(''); const [role, setRole] = useState<TenantRole>('member')
  if (data.loading) return <div className="rounded-xl border border-slate-200 bg-white p-5">Chargement de l’équipe…</div>
  if (!data.data) return <p role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{data.error || 'Équipe indisponible.'}</p>
  const permissions = data.data.permissions; const pending = (data.data.invitations || []).filter(invitation => invitation.status === 'pending')
  const submit = (event: FormEvent) => { event.preventDefault(); if (!email.trim()) return; void data.invite({ email: email.trim(), role }).then(() => setEmail('')) }
  return <div className="space-y-4">
    {!permissions?.canManageMembers && <ReadOnlyNotice message="Vous pouvez consulter l’équipe, sans modifier ses accès." />}
    <SettingsPanel title="Membres" description="Les personnes qui travaillent avec vous et leur niveau de responsabilité.">
      <div className="space-y-3">{(data.data.members || []).map(member => <article key={member.membershipId} className="flex flex-wrap items-start justify-between gap-4 rounded-lg border border-slate-200 p-4"><div className="flex gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-emerald-50 text-sm font-semibold text-emerald-700">{memberName(member).slice(0, 2).toUpperCase()}</span><div><p className="font-medium text-slate-900">{memberName(member)}</p><p className="text-sm text-slate-600">{TEAM_ROLE_LABELS[member.role]} · {member.status === 'active' ? 'Accès actif' : member.status === 'suspended' ? 'Accès suspendu' : 'Accès retiré'}</p><p className="mt-1 text-xs text-slate-500">{member.role === 'owner' ? 'Gère l’entreprise et la facturation.' : TEAM_ROLE_DESCRIPTIONS[member.role as Exclude<TenantRole, 'owner'>] || 'Responsabilités définies par votre entreprise.'}</p></div></div>{permissions?.canManageMembers && member.role !== 'owner' && <div className="flex flex-wrap gap-2"><button type="button" disabled={data.action === member.membershipId} onClick={() => void data.request(member.membershipId, `/api/team/members/${member.membershipId}/${member.status === 'suspended' ? 'reactivate' : 'suspend'}`, 'POST')} className="rounded-lg border border-slate-300 px-3 py-2 text-sm text-slate-700">{member.status === 'suspended' ? 'Réactiver' : 'Suspendre'}</button><button type="button" disabled={data.action === `remove-${member.membershipId}`} onClick={() => void data.request(`remove-${member.membershipId}`, `/api/team/members/${member.membershipId}/remove`, 'POST')} className="rounded-lg border border-red-300 px-3 py-2 text-sm text-red-700">Retirer</button></div>}</article>)}</div>
    </SettingsPanel>
    <SettingsPanel title="Invitations en attente" description="Les personnes invitées reçoivent un accès dès qu’elles acceptent.">
      {pending.length ? <div className="space-y-3">{pending.map(invitation => <div key={invitation.id} className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 pb-3 text-sm last:border-0"><div><p className="font-medium text-slate-800">{invitation.email}</p><p className="text-slate-500">{TEAM_ROLE_LABELS[invitation.role]} · envoyée le {date(invitation.createdAt)}</p></div>{permissions?.canInviteMembers && <div className="flex gap-3"><button type="button" onClick={() => void data.request(`resend-${invitation.id}`, `/api/team/invitations/${invitation.id}/resend`, 'POST')} className="text-emerald-700">Renvoyer</button><button type="button" onClick={() => void data.request(`revoke-${invitation.id}`, `/api/team/invitations/${invitation.id}/revoke`, 'POST')} className="text-red-700">Annuler</button></div>}</div>)}</div> : <p className="text-sm text-slate-500">Aucune invitation en attente.</p>}
      {permissions?.canInviteMembers && <form onSubmit={submit} className="mt-5 grid gap-3 border-t border-slate-100 pt-4 sm:grid-cols-[1fr_220px_auto]"><input type="email" required value={email} onChange={event => setEmail(event.target.value)} placeholder="prenom@entreprise.fr" className="rounded-lg border border-slate-300 px-3 py-2 text-sm" /><select value={role} onChange={event => setRole(event.target.value as TenantRole)} className="rounded-lg border border-slate-300 px-3 py-2 text-sm"><option value="admin">Administrateur</option><option value="manager">Responsable</option><option value="member">Collaborateur</option><option value="viewer">Consultation uniquement</option></select><button disabled={data.action === 'invite'} className="rounded-lg bg-emerald-600 px-4 py-2 text-sm font-medium text-white disabled:opacity-60">Inviter</button></form>}
    </SettingsPanel>
    <SettingsPanel title="Accès dans l’entreprise" description="Les responsabilités sont attribuées par rôle, pas individuellement."><div className="grid gap-3 sm:grid-cols-2"><p className="rounded-lg bg-slate-50 p-3 text-sm text-slate-700"><strong>Administrateur</strong><br />Gère les réglages, invitations et membres.</p><p className="rounded-lg bg-slate-50 p-3 text-sm text-slate-700"><strong>Responsable</strong><br />Suit l’activité sans gérer les paramètres sensibles.</p><p className="rounded-lg bg-slate-50 p-3 text-sm text-slate-700"><strong>Collaborateur</strong><br />Travaille sur les éléments qui lui sont confiés.</p><p className="rounded-lg bg-slate-50 p-3 text-sm text-slate-700"><strong>Propriétaire</strong><br />Gère également l’abonnement et les décisions d’entreprise.</p></div></SettingsPanel>
    <SettingsPanel title="Places disponibles" description="Votre offre limite le nombre d’accès à l’entreprise."><p className="text-sm text-slate-700">{data.data.seats?.unlimited ? `${data.data.seats.used} accès utilisés · illimité` : `${data.data.seats?.used || 0} / ${data.data.seats?.limit ?? 'non définie'} accès utilisés`}</p><Link href="/parametres/abonnement" className="mt-3 inline-flex text-sm font-medium text-emerald-700">Consulter l’abonnement</Link></SettingsPanel>
    {(data.error || data.message) && <p role={data.error ? 'alert' : 'status'} className={data.error ? 'text-sm text-red-600' : 'text-sm text-emerald-700'}>{data.error || data.message}</p>}
  </div>
}
