'use client';

import { CalendarClock, CircleHelp, FileText, MessageCircle, Phone } from 'lucide-react';
import type { ProjectWorkspaceProps } from './ProjectWorkspace.types';

export function ProjectActionCenter({ recommendedAction, nextAction, updating, latestDevis, onViewDevis, onWrite }: Pick<ProjectWorkspaceProps, 'recommendedAction' | 'nextAction' | 'updating' | 'latestDevis' | 'onViewDevis' | 'onWrite'>) {
  const isWaiting = nextAction.actionType === 'wait' || !recommendedAction.onClick;
  const overdue = nextAction.urgency === 'overdue';
  const deadline = overdue ? 'Échéance dépassée' : nextAction.urgency === 'today' ? "Avant aujourd’hui 18 h" : nextAction.dueLabel || 'À traiter prochainement';
  return <section aria-label="Action recommandée" className={`mt-4 flex min-h-[124px] items-center gap-5 rounded-xl border px-6 py-5 ${overdue ? 'border-orange-200 bg-orange-50/70' : 'border-emerald-100 bg-gradient-to-r from-emerald-50/80 via-white to-white'}`}>
    <span className={`flex h-14 w-14 shrink-0 items-center justify-center rounded-full ${overdue ? 'bg-orange-100 text-orange-600' : 'bg-emerald-100 text-emerald-700'}`}><Phone size={24} /></span>
    <div className="min-w-0 flex-1"><div className="flex items-center gap-2"><h2 className="text-xl font-semibold tracking-[-0.025em] text-slate-950">{recommendedAction.title}</h2><span className={`ml-auto hidden shrink-0 items-center gap-1 rounded-full px-2.5 py-1 text-[11px] font-semibold xl:inline-flex ${overdue ? 'bg-orange-100 text-orange-700' : 'bg-emerald-50 text-emerald-700'}`}><MessageCircle size={12} />Action recommandée</span></div><p className="mt-1.5 text-sm leading-5 text-slate-600">{recommendedAction.meta || 'La prochaine étape utile pour faire avancer ce dossier.'}</p>{nextAction.blockingReasons?.length > 0 && <p className="mt-2 text-sm font-medium text-orange-700">À débloquer : {nextAction.blockingReasons.join(' · ')}</p>}<p className={`mt-3 inline-flex items-center gap-1.5 text-sm font-semibold ${overdue ? 'text-orange-700' : 'text-slate-600'}`}><CalendarClock size={15} />{deadline}</p></div>
    <div className="flex shrink-0 items-center gap-2">{!isWaiting && <button type="button" onClick={recommendedAction.onClick} disabled={updating} className="inline-flex h-12 items-center gap-2 rounded-lg bg-emerald-600 px-5 text-sm font-semibold text-white transition hover:bg-emerald-700 disabled:opacity-50"><Phone size={16} />{recommendedAction.ctaLabel}</button>}{!isWaiting && latestDevis && <button type="button" onClick={onViewDevis} className="hidden h-12 items-center gap-2 rounded-lg border border-slate-200 bg-white px-4 text-sm font-semibold text-slate-700 hover:bg-slate-50 lg:inline-flex"><FileText size={16} />Voir le devis</button>}{!isWaiting && !latestDevis && <button type="button" onClick={onWrite} className="hidden h-12 rounded-lg border border-slate-200 bg-white px-4 text-sm font-semibold text-slate-700 hover:bg-slate-50 lg:inline-flex">Écrire</button>}{isWaiting && <p className="text-sm font-semibold text-slate-500">Aucun suivi requis</p>}<details className="relative"><summary aria-label="Pourquoi cette action ?" className="cursor-pointer list-none text-slate-400 hover:text-slate-700"><CircleHelp size={18} /></summary><p className="absolute right-0 z-20 mt-2 w-72 rounded-lg border border-slate-200 bg-white p-3 text-xs leading-5 text-slate-600 shadow-lg">Cette suggestion s’appuie sur l’état du dossier, les échanges récents et le cycle du devis.</p></details></div>
  </section>;
}
