'use client';

import { CircleHelp, FileText, MessageCircle, Phone } from 'lucide-react';
import type { ProjectWorkspaceProps } from './ProjectWorkspace.types';

export function ProjectActionCenter({ recommendedAction, updating, latestDevis, onViewDevis, situations }: Pick<ProjectWorkspaceProps, 'recommendedAction' | 'updating' | 'latestDevis' | 'onViewDevis' | 'situations'>) {
  const situation = situations.action;
  const hasAction = Boolean(situation.primaryAction && recommendedAction.onClick);
  const proposal = situation.recommendation?.reason || situation.reassurance || 'Je vous recommande de ne rien changer tant qu’aucun fait nouveau ne modifie la situation.';

  return <section aria-label="Situation du dossier" className="mt-4 rounded-xl border border-emerald-100 bg-gradient-to-r from-emerald-50/80 via-white to-white px-6 py-5">
    <div className="flex items-start gap-4"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-full bg-emerald-100 text-emerald-700"><Phone size={20} /></span><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><h2 className="text-lg font-semibold tracking-[-0.025em] text-slate-950">{situation.reassurance ? 'Situation maîtrisée' : 'À faire maintenant'}</h2><span className="ml-auto hidden items-center gap-1 text-xs font-semibold text-emerald-700 xl:inline-flex"><MessageCircle size={12} />Kadria veille</span></div><div className="mt-3 space-y-3 text-sm leading-6 text-slate-700"><div><p className="font-semibold text-slate-950">Situation</p>{situation.observedFacts.map((fact) => <p key={fact}>{fact}</p>)}</div><div><p className="font-semibold text-slate-950">Compréhension</p><p>{situation.understanding}</p></div><div><p className="font-semibold text-slate-950">Importance</p><p>{situation.importance || 'Aucune décision ne mérite votre attention aujourd’hui.'}</p></div><div><p className="font-semibold text-slate-950">Proposition</p><p>{proposal}</p></div>{situation.possibleConsequence && <p className="text-slate-600">{situation.possibleConsequence}</p>}</div><div className="mt-5 flex flex-wrap items-center gap-3">{hasAction ? <div><p className="mb-2 text-xs font-semibold uppercase tracking-wide text-slate-500">Action</p><button type="button" onClick={recommendedAction.onClick} disabled={updating} className="inline-flex h-11 items-center gap-2 rounded-lg bg-emerald-600 px-5 text-sm font-semibold text-white transition hover:bg-emerald-700 disabled:opacity-50"><Phone size={16} />{situation.primaryAction!.label}</button></div> : <p className="text-sm font-medium text-emerald-800">Aucune action n’est nécessaire aujourd’hui.</p>}{situation.secondaryAction && latestDevis && <button type="button" onClick={onViewDevis} className="inline-flex h-11 items-center gap-2 rounded-lg border border-slate-300 bg-white px-4 text-sm font-semibold text-slate-700 hover:bg-slate-50"><FileText size={16} />Préparer le devis</button>}<details className="relative"><summary aria-label="Précisions sur la recommandation" className="cursor-pointer list-none text-slate-400 hover:text-slate-700"><CircleHelp size={18} /></summary><p className="absolute right-0 z-20 mt-2 w-72 rounded-lg border border-slate-200 bg-white p-3 text-xs leading-5 text-slate-600 shadow-lg">Kadria s’appuie uniquement sur les informations présentes dans ce dossier. Il distingue les faits observés de sa recommandation.</p></details></div></div></div>
  </section>;
}
