'use client';

/* eslint-disable @typescript-eslint/no-explicit-any, @next/next/no-img-element */
import { CalendarDays, CheckSquare, FileText, History, Image as ImageIcon, MoreVertical } from 'lucide-react';
import type { ProjectWorkspaceProps, ProjectWorkspaceTab } from './ProjectWorkspace.types';

const tabs: Array<{ id: ProjectWorkspaceTab; label: string; icon: typeof History }> = [
  { id: 'activity', label: 'Activité', icon: History }, { id: 'commercial', label: 'Commercial', icon: FileText }, { id: 'qualification', label: 'Qualification', icon: CheckSquare }, { id: 'planning', label: 'Planning', icon: CalendarDays }, { id: 'documents', label: 'Documents', icon: ImageIcon },
];

export function ProjectWorkspaceTabs(props: Pick<ProjectWorkspaceProps, 'project' | 'latestDevis' | 'appointment' | 'activityItems' | 'activityUnavailable' | 'onCreateQuote' | 'onViewDevis' | 'onFollowUpQuote' | 'onPlanAppointment' | 'onOpenClientPortal' | 'formatDate' | 'formatDateTime' | 'formatAmount' | 'activeTab' | 'onTabChange' | 'onMarkWon' | 'onMarkLost'>) {
  const { activeTab, onTabChange } = props;
  return <section className="min-w-0 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-[0_1px_2px_rgba(15,23,42,0.03)]"><nav aria-label="Espaces métier" className="sticky top-0 z-10 flex overflow-x-auto border-b border-slate-200 bg-white px-5">{tabs.map(({ id, label, icon: Icon }) => <button type="button" key={id} onClick={() => onTabChange(id)} className={`flex shrink-0 items-center gap-2 border-b-2 px-4 py-4 text-sm font-semibold transition first:pl-0 ${activeTab === id ? 'border-emerald-500 text-slate-950' : 'border-transparent text-slate-500 hover:text-slate-800'}`}><Icon size={15} />{label}</button>)}</nav><div className="min-h-[420px] p-5">{activeTab === 'activity' && <Timeline items={props.activityItems} unavailable={props.activityUnavailable} formatDateTime={props.formatDateTime} onViewDevis={props.onViewDevis} />}{activeTab === 'commercial' && <CommercialWorkspace {...props} />}{activeTab === 'qualification' && <QualificationPanel project={props.project} onOpenClientPortal={props.onOpenClientPortal} />}{activeTab === 'planning' && <PlanningWorkspace appointment={props.appointment} onPlanAppointment={props.onPlanAppointment} formatDateTime={props.formatDateTime} />}{activeTab === 'documents' && <DocumentsWorkspace project={props.project} />}</div></section>;
}

function QualificationPanel({ project, onOpenClientPortal }: Pick<ProjectWorkspaceProps, 'project' | 'onOpenClientPortal'>) { const answers = project.tradeAnswers && typeof project.tradeAnswers === 'object' ? Object.entries(project.tradeAnswers) : []; return <div className="max-w-4xl"><h2 className="text-base font-semibold text-slate-950">Qualification</h2><p className="mt-1 text-sm text-slate-500">Les informations métier nécessaires pour préparer le chantier et le devis.</p><div className="mt-5 divide-y divide-slate-100 border-y border-slate-200">{answers.length > 0 ? answers.map(([key, value]) => <div key={key} className="grid grid-cols-[minmax(170px,0.35fr)_1fr] gap-6 py-3 text-sm"><span className="text-slate-500">{key}</span><span className="font-medium text-slate-800">{String(value)}</span></div>) : <p className="py-5 text-sm text-slate-500">Aucune réponse métier structurée pour le moment.</p>}</div>{onOpenClientPortal && <button type="button" onClick={onOpenClientPortal} className="mt-5 text-sm font-semibold text-emerald-700">Ouvrir le portail client</button>}</div>; }
function CommercialWorkspace({ latestDevis, onCreateQuote, onViewDevis, onFollowUpQuote, formatAmount, onMarkWon, onMarkLost }: Pick<ProjectWorkspaceProps, 'latestDevis' | 'onCreateQuote' | 'onViewDevis' | 'onFollowUpQuote' | 'formatAmount' | 'onMarkWon' | 'onMarkLost'>) { return <div className="max-w-4xl"><h2 className="text-base font-semibold text-slate-950">Commercial</h2>{latestDevis ? <div className="mt-5 border-y border-slate-200 py-5"><p className="text-xl font-semibold text-slate-950">{formatAmount(latestDevis.amount)}</p><p className="mt-1 text-sm text-slate-500">{latestDevis.accepted ? 'Devis accepté' : latestDevis.declined ? 'Devis refusé' : latestDevis.sent ? 'Devis envoyé' : 'Devis en préparation'}</p><div className="mt-5 flex flex-wrap gap-3"><button type="button" onClick={onViewDevis} className="rounded-lg bg-emerald-600 px-4 py-2.5 text-sm font-semibold text-white">Voir le devis</button>{latestDevis.sent && !latestDevis.accepted && !latestDevis.declined && <button type="button" onClick={onFollowUpQuote} className="rounded-lg border border-slate-200 px-4 py-2.5 text-sm font-semibold text-slate-700">Relancer</button>}{onMarkWon && <button type="button" onClick={onMarkWon} className="rounded-lg border border-emerald-200 px-4 py-2.5 text-sm font-semibold text-emerald-700">Marquer gagné</button>}{onMarkLost && <button type="button" onClick={onMarkLost} className="rounded-lg border border-slate-200 px-4 py-2.5 text-sm font-semibold text-slate-700">Marquer perdu</button>}</div></div> : <div className="mt-5 border-y border-slate-200 py-5"><p className="text-sm text-slate-500">Aucun devis n’a encore été créé.</p><button type="button" onClick={onCreateQuote} className="mt-4 rounded-lg bg-emerald-600 px-4 py-2.5 text-sm font-semibold text-white">Créer le devis</button></div>}</div>; }
function PlanningWorkspace({ appointment, onPlanAppointment, formatDateTime }: Pick<ProjectWorkspaceProps, 'appointment' | 'onPlanAppointment' | 'formatDateTime'>) { return <div className="max-w-4xl"><h2 className="text-base font-semibold text-slate-950">Planning</h2>{appointment ? <div className="mt-5 border-y border-slate-200 py-4"><p className="text-sm font-semibold text-slate-900">{formatDateTime(appointment.start)}</p><p className="mt-1 text-sm text-slate-500">{appointment.location || 'Lieu à confirmer'}</p></div> : <div className="mt-5 border-y border-slate-200 py-5"><p className="text-sm text-slate-500">Aucun rendez-vous n’est planifié.</p><button type="button" onClick={onPlanAppointment} className="mt-4 rounded-lg bg-emerald-600 px-4 py-2.5 text-sm font-semibold text-white">Planifier un rendez-vous</button></div>}</div>; }
function DocumentsWorkspace({ project }: Pick<ProjectWorkspaceProps, 'project'>) { const photos = Array.isArray(project.photos) ? project.photos.filter(Boolean) : []; return <div><h2 className="text-base font-semibold text-slate-950">Documents</h2>{photos.length ? <div className="mt-5 grid grid-cols-4 gap-3">{photos.map((photo: any, index: number) => <img key={photo?.id || photo?.url || index} src={typeof photo === 'string' ? photo : photo.url} alt="Document du chantier" className="aspect-square w-full rounded-lg border border-slate-200 object-cover" />)}</div> : <p className="mt-5 text-sm text-slate-500">Aucun document récent pour le moment.</p>}</div>; }
function Timeline({ items, unavailable, formatDateTime, onViewDevis }: { items: any[]; unavailable: boolean; formatDateTime: ProjectWorkspaceProps['formatDateTime']; onViewDevis: () => void }) { if (unavailable) return <p className="text-sm text-slate-500">Historique indisponible pour le moment.</p>; if (!items.length) return <p className="text-sm text-slate-500">Aucun événement important pour le moment.</p>; return <div><div className="mb-4 flex items-center justify-between"><h2 className="text-base font-semibold text-slate-950">Activité</h2><button type="button" className="rounded-md border border-slate-200 px-3 py-1.5 text-xs font-semibold text-slate-700">Filtrer</button></div><ol className="space-y-3">{items.slice(0, 12).map((item, index) => <li key={item.id} className="grid grid-cols-[54px_30px_minmax(0,1fr)_auto] items-center gap-3 rounded-lg border border-slate-100 bg-white px-3 py-3"><time className="text-xs font-medium text-slate-500">{index === 0 ? formatDateTime(item.createdAt).split(' ').slice(-1)[0] : formatDateTime(item.createdAt).split(' ')[0]}</time><span className={`flex h-8 w-8 items-center justify-center rounded-full ${item.tone === 'error' ? 'bg-red-50 text-red-600' : item.tone === 'success' ? 'bg-emerald-50 text-emerald-700' : 'bg-sky-50 text-sky-700'}`}><History size={14} /></span><div className="min-w-0"><p className="truncate text-sm font-semibold text-slate-900">{item.title}</p>{item.detail && item.detail !== item.title && <p className="mt-0.5 truncate text-xs text-slate-500">{item.detail}</p>}</div>{String(item.action || '').includes('DEVIS') && <button type="button" onClick={onViewDevis} className="hidden rounded-md border border-slate-200 px-3 py-1.5 text-xs font-semibold text-slate-700 hover:bg-slate-50 lg:inline-flex">Voir le devis</button>}<button type="button" aria-label="Plus d’actions" className="text-slate-400 hover:text-slate-700"><MoreVertical size={17} /></button></li>)}</ol><button type="button" className="mt-5 w-full text-center text-sm font-semibold text-emerald-700">Voir toute l’activité</button></div>; }
