'use client';

/* eslint-disable @typescript-eslint/no-explicit-any, @next/next/no-img-element */
import { CalendarDays, CheckSquare, FileText, History, Image as ImageIcon } from 'lucide-react';
import type { ProjectWorkspaceProps, ProjectWorkspaceTab } from './ProjectWorkspace.types';

const tabs: Array<{ id: ProjectWorkspaceTab; label: string; icon: typeof History }> = [
  { id: 'activity', label: 'Activité', icon: History }, { id: 'commercial', label: 'Commercial', icon: FileText }, { id: 'qualification', label: 'Qualification', icon: CheckSquare }, { id: 'planning', label: 'Planning', icon: CalendarDays }, { id: 'documents', label: 'Documents', icon: ImageIcon },
];

type TabProps = Pick<ProjectWorkspaceProps, 'project' | 'latestDevis' | 'appointment' | 'activityItems' | 'activityUnavailable' | 'formatDateTime' | 'formatAmount' | 'activeTab' | 'onTabChange' | 'situations'>;

export function ProjectWorkspaceTabs(props: TabProps) {
  const { activeTab, onTabChange } = props;
  return <section className="min-w-0 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-[0_1px_2px_rgba(15,23,42,0.03)]"><nav aria-label="Espaces métier" className="sticky top-0 z-10 flex overflow-x-auto border-b border-slate-200 bg-white px-5">{tabs.map(({ id, label, icon: Icon }) => <button type="button" key={id} onClick={() => onTabChange(id)} className={`flex shrink-0 items-center gap-2 border-b-2 px-4 py-4 text-sm font-semibold transition first:pl-0 ${activeTab === id ? 'border-emerald-500 text-slate-950' : 'border-transparent text-slate-500 hover:text-slate-800'}`}><Icon size={15} />{label}</button>)}</nav><div className="min-h-[420px] p-5">{activeTab === 'activity' && <ActivityWorkspace {...props} />}{activeTab === 'commercial' && <CommercialWorkspace {...props} />}{activeTab === 'qualification' && <QualificationWorkspace {...props} />}{activeTab === 'planning' && <PlanningWorkspace {...props} />}{activeTab === 'documents' && <DocumentsWorkspace {...props} />}</div></section>;
}

function SituationNarrative({ situation, title }: { situation: ProjectWorkspaceProps['situations']['activity']; title: string }) { return <div className="max-w-4xl"><h2 className="text-base font-semibold text-slate-950">{title}</h2><div className="mt-4 space-y-4"><div><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Ce que Kadria observe</p>{situation.observedFacts.map((fact) => <p key={fact} className="mt-1 text-sm leading-6 text-slate-800">{fact}</p>)}</div><div><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Ce qu’il comprend</p><p className="mt-1 text-sm leading-6 text-slate-800">{situation.understanding}</p></div>{situation.importance && <div><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Pourquoi il en parle</p><p className="mt-1 text-sm leading-6 text-slate-700">{situation.importance}</p></div>}{situation.reassurance && <p className="rounded-lg bg-emerald-50 px-4 py-3 text-sm leading-6 text-emerald-900">{situation.reassurance}</p>}</div></div>; }

function ActivityWorkspace({ activityItems, activityUnavailable, formatDateTime, situations }: TabProps) { if (activityUnavailable) return <SituationNarrative title="Depuis votre dernière visite" situation={{ ...situations.activity, observedFacts: ['L’historique détaillé est indisponible pour le moment.'] }} />; const significant = activityItems.filter((item) => item.tone === 'error' || item.tone === 'success' || String(item.action || '').includes('DEVIS')); return <div><SituationNarrative title="Depuis votre dernière visite" situation={situations.activity} />{significant.length > 0 && <details className="mt-7 border-t border-slate-200 pt-5"><summary className="cursor-pointer text-sm font-semibold text-slate-700">Ouvrir l’historique détaillé</summary><ol className="mt-4 space-y-3">{significant.slice(0, 12).map((item, index) => <li key={item.id || index} className="rounded-lg border border-slate-100 px-4 py-3"><p className="text-sm font-semibold text-slate-900">{item.detail || item.title}</p><p className="mt-1 text-xs text-slate-500">{formatDateTime(item.createdAt)}</p></li>)}</ol></details>}</div>; }

function CommercialWorkspace({ situations, latestDevis, formatAmount }: TabProps) { const situation = situations.commercial; const confidence = situation.confidence === 'high' ? 'Élevé' : situation.confidence === 'medium' ? 'Modéré' : situation.confidence === 'low' ? 'Limité' : null; return <div><SituationNarrative title="Situation commerciale" situation={situation} />{confidence && <p className="mt-5 text-sm text-slate-700"><span className="font-semibold text-slate-950">Niveau de confiance : </span>{confidence}. Kadria s’appuie uniquement sur les éléments confirmés.</p>}{latestDevis && <dl className="mt-7 grid max-w-xl grid-cols-2 gap-x-8 gap-y-3 border-y border-slate-200 py-4 text-sm"><dt className="text-slate-500">Montant</dt><dd className="text-right font-semibold text-slate-950">{formatAmount(latestDevis.amount)}</dd>{latestDevis.quote_sent_at && <><dt className="text-slate-500">Envoyé le</dt><dd className="text-right text-slate-800">{latestDevis.quote_sent_at}</dd></>}{Number(latestDevis.opens_count) > 0 && <><dt className="text-slate-500">Consultations</dt><dd className="text-right text-slate-800">{latestDevis.opens_count}</dd></>}</dl>}</div>; }

function QualificationWorkspace({ situations }: TabProps) { const situation = situations.qualification; const confirmed = situation.observedFacts[0]?.replace('Informations confirmées : ', '').replace('.', '').split(', ').filter(Boolean) || []; return <div><SituationNarrative title="Niveau de compréhension du projet" situation={situation} /><div className="mt-7 grid gap-6 border-t border-slate-200 pt-5 sm:grid-cols-2"><div><p className="text-sm font-semibold text-slate-950">Informations confirmées</p>{confirmed.length ? <ul className="mt-3 space-y-2 text-sm text-slate-700">{confirmed.map((item) => <li key={item}>✓ {item}</li>)}</ul> : <p className="mt-3 text-sm text-slate-500">Aucune information confirmée n’est mise en avant.</p>}</div>{situation.missingInformation && situation.missingInformation.length > 0 && <div><p className="text-sm font-semibold text-slate-950">Informations encore utiles</p><ul className="mt-3 space-y-2 text-sm text-slate-700">{situation.missingInformation.map((item) => <li key={item}>○ {item}</li>)}</ul></div>}</div></div>; }

function PlanningWorkspace({ situations, appointment, formatDateTime }: TabProps) { const situation = situations.planning; return <div><SituationNarrative title="Préparer le prochain engagement" situation={situation} />{appointment?.start && <div className="mt-7 space-y-5 border-t border-slate-200 pt-5"><div><p className="text-sm font-semibold text-slate-950">Objectif du rendez-vous</p><p className="mt-1 text-sm leading-6 text-slate-700">Confirmer les éléments nécessaires avant la prochaine décision du dossier.</p></div>{situation.preparation && <div><p className="text-sm font-semibold text-slate-950">Préparation</p><ul className="mt-2 space-y-1 text-sm leading-6 text-slate-700">{situation.preparation.map((item) => <li key={item}>— {item}</li>)}</ul></div>}{situation.risks && <div><p className="text-sm font-semibold text-slate-950">Point à sécuriser</p>{situation.risks.map((risk) => <p key={risk} className="mt-1 text-sm leading-6 text-slate-700">{risk}</p>)}</div>}<div><p className="text-sm font-semibold text-slate-950">Résultat attendu</p><p className="mt-1 text-sm leading-6 text-slate-700">{situation.expectedOutcome || 'Le prochain élément déterminant du dossier sera clarifié.'}</p></div><div className="border-t border-slate-100 pt-5"><p className="text-sm font-semibold text-slate-950">{formatDateTime(appointment.start)}</p><p className="mt-1 text-sm text-slate-600">{appointment.location || 'Lieu à confirmer'}</p></div></div>}</div>; }

function DocumentsWorkspace({ project, situations }: TabProps) { const photos = Array.isArray(project.photos) ? project.photos.filter(Boolean) : []; const situation = situations.documents; return <div><SituationNarrative title="Documents utiles pour avancer" situation={situation} />{situation.preparation && <div className="mt-6 border-t border-slate-200 pt-5"><p className="text-sm font-semibold text-slate-950">Ce qu’ils permettent de confirmer</p>{situation.preparation.map((item) => <p key={item} className="mt-1 text-sm leading-6 text-slate-700">{item}</p>)}{situation.expectedOutcome && <p className="mt-4 text-sm leading-6 text-slate-700">{situation.expectedOutcome}</p>}</div>}{photos.length > 0 && <div className="mt-7 border-t border-slate-200 pt-5"><p className="text-sm font-semibold text-slate-950">Preuves disponibles</p><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4">{photos.map((photo: any, index: number) => <img key={photo?.id || photo?.url || index} src={typeof photo === 'string' ? photo : photo.url} alt="Photo utile au dossier" className="aspect-square w-full rounded-lg border border-slate-200 object-cover" />)}</div></div>}</div>; }
