'use client';

/* eslint-disable @typescript-eslint/no-explicit-any, @next/next/no-img-element */
import { CalendarClock, FileText, Mail, MapPin, Phone, UserRound } from 'lucide-react';
import type { ProjectWorkspaceProps } from './ProjectWorkspace.types';

export function ProjectContextSidebar({ project, appointment, responsibleName, latestDevis, decision, formatDate, formatDateTime, formatAmount, onCall, onWrite, onViewDevis, onPlanAppointment, onEditProject }: Pick<ProjectWorkspaceProps, 'project' | 'appointment' | 'responsibleName' | 'latestDevis' | 'decision' | 'formatDate' | 'formatDateTime' | 'formatAmount' | 'onCall' | 'onWrite' | 'onViewDevis' | 'onPlanAppointment' | 'onEditProject'>) {
  const address = [project.siteAddress, project.postalCode, project.city].filter(Boolean).join(', ');
  const photos = Array.isArray(project.photos) ? project.photos.filter(Boolean).slice(0, 4) : [];
  const quoteStatus = latestDevis?.accepted ? 'Accepté' : latestDevis?.declined ? 'Refusé' : latestDevis?.sent ? 'Envoyé' : latestDevis ? 'En préparation' : null;
  return <aside className="min-w-0 space-y-3 self-start xl:sticky xl:top-4">
    <section className="rounded-xl border border-slate-200 bg-white p-4 shadow-[0_1px_2px_rgba(15,23,42,0.03)]"><div className="flex items-center justify-between gap-3"><h2 className="flex items-center gap-2 text-sm font-semibold text-slate-950"><UserRound size={15} />Client</h2><button type="button" onClick={onEditProject} className="text-xs font-semibold text-slate-500 hover:text-slate-900">Modifier</button></div><div className="mt-3 flex items-start gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-emerald-50 text-sm font-semibold text-emerald-700">{[project.clientFirstName?.[0], project.clientName?.[0]].filter(Boolean).join('').toUpperCase() || '—'}</span><div className="min-w-0"><p className="truncate text-sm font-semibold text-slate-950">{[project.clientFirstName, project.clientName].filter(Boolean).join(' ') || 'Client non renseigné'}</p>{project.clientPhone && <p className="mt-1 flex items-center gap-1.5 text-xs text-slate-600"><Phone size={12} />{project.clientPhone}</p>}{project.clientEmail && <p className="mt-1 flex items-center gap-1.5 truncate text-xs text-slate-600"><Mail size={12} />{project.clientEmail}</p>}</div></div>{address && <a target="_blank" rel="noreferrer" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(address)}`} className="mt-3 flex items-start gap-1.5 text-xs leading-5 text-slate-600 hover:text-emerald-700"><MapPin className="mt-0.5 shrink-0" size={13} />{address}</a>}<div className="mt-3 flex gap-2"><button type="button" onClick={onCall} className="inline-flex flex-1 items-center justify-center gap-1.5 rounded-md border border-slate-200 px-2.5 py-2 text-xs font-semibold text-slate-700 hover:bg-slate-50"><Phone size={13} />Appeler</button><button type="button" onClick={onWrite} className="inline-flex flex-1 items-center justify-center gap-1.5 rounded-md border border-slate-200 px-2.5 py-2 text-xs font-semibold text-slate-700 hover:bg-slate-50"><Mail size={13} />Écrire</button></div></section>
    {latestDevis && <section className="rounded-xl border border-slate-200 bg-white p-4 shadow-[0_1px_2px_rgba(15,23,42,0.03)]"><div className="flex items-center justify-between"><h2 className="flex items-center gap-2 text-sm font-semibold text-slate-950"><FileText size={15} />Devis</h2><button type="button" onClick={onViewDevis} className="text-xs font-semibold text-emerald-700 hover:text-emerald-800">Voir</button></div><div className="mt-3 flex items-center justify-between"><span className="text-xs text-slate-500">Statut</span><span className="rounded-md bg-emerald-50 px-2 py-1 text-xs font-semibold text-emerald-700">{quoteStatus}</span></div><div className="mt-2 grid grid-cols-2 gap-y-2 text-xs"><span className="text-slate-500">Montant</span><strong className="text-right text-slate-900">{formatAmount(latestDevis.amount)}</strong>{latestDevis.quote_sent_at && <><span className="text-slate-500">Envoyé le</span><strong className="text-right text-slate-900">{formatDate(latestDevis.quote_sent_at)}</strong></>}{latestDevis.opens_count > 0 && <><span className="text-slate-500">Ouvert</span><strong className="text-right text-slate-900">{latestDevis.opens_count} fois</strong></>}</div>{decision?.canFollowUpQuote && <div className="mt-3 flex items-center gap-1.5 border-t border-slate-100 pt-3 text-xs font-semibold text-orange-700"><CalendarClock size={13} />Relance à prévoir</div>}</section>}
    <section className="rounded-xl border border-slate-200 bg-white p-4 shadow-[0_1px_2px_rgba(15,23,42,0.03)]"><div className="flex items-center justify-between"><h2 className="flex items-center gap-2 text-sm font-semibold text-slate-950"><CalendarClock size={15} />Prochain engagement</h2>{appointment && <button type="button" onClick={onPlanAppointment} className="text-xs font-semibold text-slate-500 hover:text-slate-900">Modifier</button>}</div>{appointment ? <div className="mt-3"><p className="text-sm font-semibold text-slate-900">{formatDateTime(appointment.start)}</p><p className="mt-1 text-xs text-slate-500">{appointment.location || 'Lieu à confirmer'}</p><p className="mt-2 text-xs text-slate-600">{responsibleName || appointment.assignedUserName || 'Responsable à définir'}</p></div> : <div className="mt-3"><p className="text-sm text-slate-600">Aucun rendez-vous à venir.</p><button type="button" onClick={onPlanAppointment} className="mt-3 text-xs font-semibold text-emerald-700 hover:text-emerald-800">Planifier un rendez-vous</button></div>}</section>
    {photos.length > 0 && <section className="rounded-xl border border-slate-200 bg-white p-4 shadow-[0_1px_2px_rgba(15,23,42,0.03)]"><div className="flex items-center justify-between"><h2 className="text-sm font-semibold text-slate-950">Documents récents</h2><span className="text-xs text-slate-500">{Array.isArray(project.photos) ? project.photos.length : photos.length}</span></div><div className="mt-3 flex gap-2">{photos.map((photo: any, index: number) => <img key={photo?.id || photo?.url || index} src={typeof photo === 'string' ? photo : photo.url} alt="Document du chantier" className="h-12 w-12 rounded-md border border-slate-100 object-cover" />)}{Array.isArray(project.photos) && project.photos.length > photos.length && <span className="flex h-12 w-12 items-center justify-center rounded-md border border-slate-200 bg-slate-50 text-xs font-semibold text-slate-600">+{project.photos.length - photos.length}</span>}</div></section>}
  </aside>;
}
