import { cleanup, render, screen, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { afterEach, expect, test, vi } from 'vitest'
import { ProjectPipelineActionAdapter } from '../actions/ProjectPipelineActionAdapter'
import { ProjectPipelineDialog } from '../dialogs/ProjectPipelineDialog'
vi.mock('next/navigation', () => ({ useRouter: () => ({ push: vi.fn() }) }))
const reply = (status: number, body: unknown) => new Response(JSON.stringify(body), { status, headers: { 'Content-Type': 'application/json' } })
const pipeline = { currentStage: 'Devis envoyé', commercialStatus: 'Devis envoyé', outcome: null, allowedTransitions: ['Gagné', 'Perdu'], primaryAction: { action: 'move', targetStage: 'Gagné' }, quote: { id: 'q1', number: 'D-1', status: 'Envoyé' } }
afterEach(() => { cleanup(); vi.unstubAllGlobals() })
test('adapter reads the minimal DTO and sends intentional commands only', async () => { const fetch = vi.fn().mockResolvedValueOnce(reply(200, { success: true, pipeline })).mockResolvedValueOnce(reply(200, { success: true })); vi.stubGlobal('fetch', fetch); const adapter = new ProjectPipelineActionAdapter('p1'); await expect(adapter.read()).resolves.toMatchObject({ success: true, pipeline }); await expect(adapter.execute({ action: 'mark_won' })).resolves.toEqual({ success: true }); expect(fetch.mock.calls[1][1].body).toBe(JSON.stringify({ action: 'mark_won' })) })
test('dialog loads once on open, confirms a terminal command once and refreshes targeted orchestrator once', async () => { let resolve!: (value: Response) => void; const pending = new Promise<Response>((r) => { resolve = r }); const fetch = vi.fn().mockResolvedValueOnce(reply(200, { success: true, pipeline })).mockReturnValueOnce(pending); vi.stubGlobal('fetch', fetch); const user = userEvent.setup(); const close = vi.fn(); const saved = vi.fn().mockResolvedValue(undefined); render(<ProjectPipelineDialog projectId="p1" onClose={close} onSaved={saved} />); expect(await screen.findByText('État actuel :')).toBeVisible(); await user.click(screen.getByRole('button', { name: 'Gagné' })); expect(screen.getAllByRole('button', { name: 'Enregistrement…' })).toHaveLength(2); expect(fetch).toHaveBeenCalledTimes(2); resolve(reply(200, { success: true })); await waitFor(() => expect(close).toHaveBeenCalledOnce()); expect(saved).toHaveBeenCalledOnce() })
test('dialog keeps the state open after a business error and exposes no loss reason field', async () => { const fetch = vi.fn().mockResolvedValueOnce(reply(200, { success: true, pipeline })).mockResolvedValueOnce(reply(409, { success: false, error: 'Transition commerciale interdite.' })); vi.stubGlobal('fetch', fetch); const user = userEvent.setup(); render(<ProjectPipelineDialog projectId="p1" onClose={vi.fn()} onSaved={vi.fn()} />); await screen.findByText('État actuel :'); expect(screen.queryByLabelText(/motif/i)).toBeNull(); await user.click(screen.getByRole('button', { name: 'Perdu' })); expect(await screen.findByText('Transition commerciale interdite.')).toBeVisible(); expect(screen.getByRole('dialog')).toBeVisible() })
