'use client'

import Link from 'next/link'
import { ReadOnlyNotice } from '@/src/components/settings/ReadOnlyNotice'
import { SettingsPanel } from '@/src/components/settings/SettingsPanel'
import { useAutomationSettingsData, type AutomationItem } from '@/src/hooks/useAutomationSettingsData'

const autonomy = { manual: 'Toujours me demander', approval_required: 'Me proposer', automatic: 'Agir automatiquement' } as const
const date = (value: string | null) => value ? new Date(value).toLocaleString('fr-FR') : 'Jamais'

function AutomationCard({ item, data }: { item: AutomationItem; data: ReturnType<typeof useAutomationSettingsData> }) {
  const update = (patch: Partial<AutomationItem['automation']>) => data.setItems(current => current.map(row => row.automation.type === item.automation.type ? { ...row, automation: { ...row.automation, ...patch } } : row))
  const disabled = !data.permissions.canManage || data.systemState.paused
  return <article className="rounded-lg border border-slate-200 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-medium text-slate-900">{item.definition.title}</h3><p className="mt-1 text-sm text-slate-600">{item.definition.description}</p></div><span className={item.automation.enabled ? 'rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-medium text-emerald-700' : 'rounded-full bg-slate-100 px-2.5 py-1 text-xs font-medium text-slate-600'}>{item.automation.enabled ? 'Active' : 'Inactive'}</span></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><div><p className="text-xs font-medium uppercase tracking-wide text-slate-500">Quand</p><p className="mt-1 text-sm text-slate-700">{item.automation.delayValue ? `Après ${item.automation.delayValue} ${item.automation.delayUnit === 'hours' ? 'heure(s)' : 'jour(s)'}` : 'Quand Kadria détecte une situation utile'}</p></div><div><p className="text-xs font-medium uppercase tracking-wide text-slate-500">Conséquence</p><p className="mt-1 text-sm text-slate-700">{item.automation.mode === 'automatic' ? 'Kadria réalise l’action autorisée.' : 'Kadria vous laisse la décision finale.'}</p></div></div><label className="mt-4 block text-sm font-medium text-slate-700">Niveau d’autonomie<select disabled={disabled} value={item.automation.mode} onChange={event => update({ mode: event.target.value as AutomationItem['automation']['mode'] })} className="mt-1 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 disabled:bg-slate-50">{(Object.entries(autonomy) as Array<[AutomationItem['automation']['mode'], string]>).filter(([mode]) => mode !== 'automatic' || item.definition.automaticAllowed).map(([mode, label]) => <option key={mode} value={mode}>{label}</option>)}</select></label>{item.automation.lastErrorMessage && <p role="alert" className="mt-3 rounded-lg bg-red-50 p-3 text-sm text-red-700">À revoir : {item.automation.lastErrorMessage}</p>}<div className="mt-4 flex flex-wrap items-center gap-3"><button type="button" disabled={disabled} onClick={() => update({ enabled: !item.automation.enabled })} className="rounded-lg border border-slate-300 px-3 py-2 text-sm font-medium text-slate-700 disabled:opacity-60">{item.automation.enabled ? 'Désactiver' : 'Activer'}</button><button type="button" disabled={disabled || data.mutating === item.automation.type} onClick={() => void data.save(item)} className="rounded-lg bg-emerald-600 px-3 py-2 text-sm font-medium text-white disabled:opacity-60">{data.mutating === item.automation.type ? 'Enregistrement…' : 'Enregistrer'}</button><span className="text-xs text-slate-500">Dernière action : {date(item.automation.lastRunAt)}</span></div></article>
}

export function AutomationSettingsView() {
  const data = useAutomationSettingsData()
  if (data.error && !data.loading && !data.permissions.canRead) return <div role="alert" className="rounded-xl border border-amber-200 bg-amber-50 p-5 text-sm text-amber-900"><p>{data.error}</p><button type="button" onClick={() => void data.load()} className="mt-3 rounded-lg border border-amber-300 bg-white px-3 py-2 font-medium">Réessayer</button></div>
  if (data.loading) return <div className="rounded-xl border border-slate-200 bg-white p-5">Chargement des automatisations…</div>
  if (!data.permissions.canRead) return <ReadOnlyNotice message="Vous n’avez pas accès aux automatisations." />
  return <div className="space-y-4">
    {!data.permissions.canManage && <ReadOnlyNotice message="Vous pouvez consulter les automatismes, sans modifier leur autonomie." />}
    <SettingsPanel title="Ce que Kadria peut faire" description="Activez les aides qui vous font gagner du temps et choisissez leur niveau d’autonomie.">
      <div className="space-y-3">{data.items.map(item => <AutomationCard key={item.automation.type} item={item} data={data} />)}</div>
    </SettingsPanel>
    <SettingsPanel title="Niveau d’autonomie" description="Toujours me demander : vous décidez. Me proposer : Kadria prépare. Agir automatiquement : Kadria exécute dans le cadre autorisé.">
      <div className="grid gap-3 sm:grid-cols-3">{Object.values(autonomy).map((label, index) => <div key={label} className="rounded-lg bg-slate-50 p-4"><p className="font-medium text-slate-900">{label}</p><p className="mt-1 text-sm text-slate-600">{index === 0 ? 'Aucune action sans vous.' : index === 1 ? 'Une action claire à valider.' : 'Une action réalisée sans attente.'}</p></div>)}</div>
    </SettingsPanel>
    <SettingsPanel title="Historique récent" description="Les dernières actions de Kadria, présentées simplement.">
      <div className="space-y-3">{data.recentRuns.length ? data.recentRuns.slice(0, 4).map(run => <div key={run.id} className="flex flex-wrap items-center justify-between gap-2 border-b border-slate-100 pb-3 text-sm last:border-0"><div><p className="font-medium text-slate-800">{run.automationTitle}</p><p className="text-slate-500">{run.statusLabel}{run.errorLabel ? ` · ${run.errorLabel}` : ''}</p></div><time className="text-slate-500">{date(run.createdAt)}</time></div>) : <p className="text-sm text-slate-500">Aucune action récente.</p>}</div><Link href="/parametres/automatisations/historique" className="mt-4 inline-flex text-sm font-medium text-emerald-700">Voir tout le journal des actions</Link>
    </SettingsPanel>
    <section className={data.systemState.paused ? 'rounded-xl border border-amber-300 bg-amber-50 p-5' : 'rounded-xl border border-slate-200 bg-white p-5 shadow-sm'}><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="text-base font-semibold text-slate-900">Pause générale</h2><p className="mt-1 text-sm text-slate-600">Pendant cette pause, Kadria continue d’observer mais n’exécute aucune action.</p></div>{data.permissions.canManage && <button type="button" onClick={() => void data.pause()} disabled={data.mutating === 'pause'} className="rounded-lg border border-slate-300 bg-white px-4 py-2 text-sm font-medium text-slate-700 disabled:opacity-60">{data.mutating === 'pause' ? 'Mise à jour…' : data.systemState.paused ? 'Reprendre les automatisations' : 'Mettre en pause'}</button>}</div>{data.error && <p role="alert" className="mt-3 text-sm text-red-600">{data.error}</p>}</section>
  </div>
}
