import assert from 'node:assert/strict'
import { register } from 'node:module'
import test from 'node:test'
register('../../__tests__/typescript-resolution.loader.mjs', import.meta.url)
const { buildTrackingBrief } = (await import('../tracking-brief-builder')) as typeof import('../tracking-brief-builder')
const project = (overrides: Record<string, unknown> = {}) => ({ id: 'p1', status: 'Qualifié', clientName: 'Martin', clientFirstName: 'Léa', projectType: 'Rénovation', trade: '', budget: '8000', devisAmount: 0, completenessScore: 90, createdAt: '2026-07-01T00:00:00Z', updatedAt: '2026-07-01T00:00:00Z', callbackDate: '', quoteSentAt: null, acceptedAt: null, lastFollowUpAt: null, ...overrides })
test('keeps a strict compact payload and limits opportunities', () => { const brief = buildTrackingBrief(Array.from({ length: 20 }, (_, index) => project({ id: `p${index}`, quoteSentAt: '2026-07-01T00:00:00Z' })), { now: new Date('2026-07-20T00:00:00Z') }); assert.deepEqual(Object.keys(brief).sort(), ['dataQuality', 'generatedAt', 'opportunities', 'workspace']); assert.equal(brief.opportunities.length, 12); assert.equal(brief.workspace?.projects.length, 5); assert.equal('events' in brief, false); assert.equal('kpis' in brief, false) })
test('represents empty, partial and insufficient data without overclaiming', () => { assert.equal(buildTrackingBrief([], { now: new Date() }).opportunities.length, 0); assert.equal(buildTrackingBrief([], { reservations: ['Données limitées'] }).dataQuality.level, 'partial'); assert.equal(buildTrackingBrief([], { insufficient: true }).dataQuality.level, 'insufficient') })
test('uses evidence levels and a cautious inactive signal', () => { const brief = buildTrackingBrief([project({ quoteSentAt: '2026-07-01T00:00:00Z' }), project({ id: 'p2', completenessScore: 20 }), project({ id: 'p3', status: 'Nouveau', completenessScore: 90, callbackDate: '2026-06-02T00:00:00Z', updatedAt: '2026-06-01T00:00:00Z' })], { now: new Date('2026-07-20T00:00:00Z') }); assert.equal(brief.opportunities[0].evidenceLevel, 'strong'); assert.match(brief.opportunities.find((item) => item.id === 'inactive-p3')?.uncertainty || '', /peut indiquer/) })
test('projects the existing statuses into the six commercial stages without mixing estimate budgets into quote values', () => { const brief = buildTrackingBrief([project({ id: 'new', status: 'Nouveau', budget: '9000' }), project({ id: 'quote', status: 'Devis envoyé', quoteSentAt: '2026-07-18T00:00:00Z', devisAmount: 12000 }), project({ id: 'won', status: 'Gagné', acceptedAt: '2026-07-20T00:00:00Z', devisAmount: 8000 })], { now: new Date('2026-07-20T00:00:00Z') }); assert.equal(brief.workspace?.pipeline.find((item) => item.key === 'new')?.count, 1); assert.equal(brief.workspace?.pipeline.find((item) => item.key === 'quote_sent')?.quoteAmount, 12000); assert.equal(brief.workspace?.quoteValueInProgress, 12000) })
test('reconstructs only dated movements and applies stage-specific slowdown thresholds', () => { const brief = buildTrackingBrief([project({ id: 'recent', quoteSentAt: '2026-07-20T00:00:00Z', updatedAt: '2026-07-20T00:00:00Z' }), project({ id: 'slow-quote', quoteSentAt: '2026-07-10T00:00:00Z' }), project({ id: 'slow-new', status: 'Nouveau', updatedAt: '2026-07-05T00:00:00Z' })], { now: new Date('2026-07-20T00:00:00Z') }); assert.equal(brief.workspace?.movements[0]?.projectId, 'recent'); assert.equal(brief.workspace?.slowdowns.some((item) => item.projectId === 'slow-quote'), true); assert.equal(brief.workspace?.slowdowns.some((item) => item.projectId === 'slow-new'), true) })
test('keeps unauthenticated and server-error responses explicit in the route', async () => { const { readFile } = await import('node:fs/promises'); const source = await readFile(new URL('../../../../../app/api/tracking-brief/route.ts', import.meta.url), 'utf8'); assert.match(source, /status: 401/); assert.match(source, /status: 500/); assert.match(source, /export const dynamic = 'force-dynamic'/) })
