'use client'

import Link from 'next/link'
import { useEffect, useState } from 'react'
import { hasPermission } from '@/src/lib/team/permission-matrix'
import type { TenantRole } from '@/src/lib/team/types'
import { ReadOnlyNotice } from '@/src/components/settings/ReadOnlyNotice'
import { SettingsPanel } from '@/src/components/settings/SettingsPanel'

type Values = { devisValidite: string; devisTvaDefaut: string; devisConditionsPaiement: string; devisMentionLegale: string; devisPrefixe: string; defaultDepositPercent: string; defaultEstimatedDelay: string }
const empty: Values = { devisValidite: '90', devisTvaDefaut: '20', devisConditionsPaiement: '', devisMentionLegale: '', devisPrefixe: 'DEV', defaultDepositPercent: '', defaultEstimatedDelay: '' }
const field = 'mt-1 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm text-slate-900 outline-none focus:border-emerald-500 focus:ring-2 focus:ring-emerald-100 disabled:bg-slate-50'

export function QuoteSettingsView() {
  const [values, setValues] = useState<Values>(empty); const [role, setRole] = useState<TenantRole | null>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState<string | null>(null); const [messages, setMessages] = useState<Record<string, string>>({})
  const canEdit = role !== null && hasPermission(role, 'business_settings.update')
  const load = async () => { setLoading(true); try { const [config, team] = await Promise.all([fetch('/api/artisan/config'), fetch('/api/team')]); const [configData, teamData] = await Promise.all([config.json(), team.json().catch(() => null)]); if (!configData.success) throw new Error(configData.error || 'Les réglages de devis sont indisponibles.'); const c = configData.config || {}; const q = c.businessConfig?.quoteSettings || {}; setValues({ devisValidite: String(c.devisValidite ?? 90), devisTvaDefaut: String(c.devisTvaDefaut ?? 20), devisConditionsPaiement: c.devisConditionsPaiement || '', devisMentionLegale: c.devisMentionLegale || '', devisPrefixe: c.devisPrefixe || 'DEV', defaultDepositPercent: q.defaultDepositPercent == null ? '' : String(q.defaultDepositPercent), defaultEstimatedDelay: q.defaultEstimatedDelay || '' }); if (teamData?.membership?.role) setRole(teamData.membership.role as TenantRole); else setMessages({ load: 'Les autorisations n’ont pas pu être vérifiées.' }) } catch (error) { setMessages({ load: error instanceof Error ? error.message : 'Les réglages de devis sont indisponibles.' }) } finally { setLoading(false) } }
  useEffect(() => { void load() }, [])
  const update = <K extends keyof Values>(key: K, value: Values[K]) => setValues(current => ({ ...current, [key]: value }))
  const save = async (domain: string, patch: Record<string, unknown>) => { setSaving(domain); setMessages(current => ({ ...current, [domain]: '' })); try { const response = await fetch('/api/artisan/config', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(patch) }); const data = await response.json(); if (!data.success) throw new Error(data.error || 'Enregistrement impossible.'); setMessages(current => ({ ...current, [domain]: 'Enregistré.' })) } catch (error) { setMessages(current => ({ ...current, [domain]: error instanceof Error ? error.message : 'Enregistrement impossible.' })) } finally { setSaving(null) } }
  const action = (domain: string, label: string, patch: Record<string, unknown>) => <div className="mt-4 flex items-center gap-3"><button type="button" disabled={!canEdit || saving === domain} onClick={() => void save(domain, patch)} className="rounded-lg bg-emerald-600 px-4 py-2 text-sm font-medium text-white disabled:opacity-60">{saving === domain ? 'Sauvegarde…' : label}</button>{messages[domain] && <p role={messages[domain] === 'Enregistré.' ? 'status' : 'alert'} className="text-sm text-slate-700">{messages[domain]}</p>}</div>
  if (loading) return <p role="status" className="rounded-xl border border-slate-200 bg-white p-5 text-sm text-slate-600">Chargement des réglages de devis…</p>
  if (messages.load) return <p role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{messages.load}</p>
  return <div className="space-y-4">{!canEdit && <ReadOnlyNotice message="Les réglages de devis sont en lecture seule pour votre rôle." />}
    <SettingsPanel title="Réglages par défaut" description="Ces valeurs sont proposées automatiquement lors de la création d’un devis et peuvent être ajustées pour chaque dossier." status="complete"><fieldset disabled={!canEdit} className="grid gap-4 md:grid-cols-2"><label className="text-sm font-medium text-slate-700">Durée de validité (jours)<input className={field} type="number" min="1" value={values.devisValidite} onChange={e => update('devisValidite', e.target.value)} /></label><label className="text-sm font-medium text-slate-700">Taux de TVA par défaut<select className={field} value={values.devisTvaDefaut} onChange={e => update('devisTvaDefaut', e.target.value)}>{[0, 5.5, 10, 20].map(rate => <option key={rate}>{rate}</option>)}</select></label><label className="text-sm font-medium text-slate-700">Acompte conseillé (%)<input className={field} type="number" min="0" max="100" value={values.defaultDepositPercent} onChange={e => update('defaultDepositPercent', e.target.value)} /></label><label className="text-sm font-medium text-slate-700">Délai estimé par défaut<input className={field} value={values.defaultEstimatedDelay} onChange={e => update('defaultEstimatedDelay', e.target.value)} placeholder="Ex. 2 à 3 semaines" /></label></fieldset>{action('defaults', 'Enregistrer les valeurs par défaut', { devisValidite: Number(values.devisValidite), devisTvaDefaut: Number(values.devisTvaDefaut), businessConfig: { quoteSettings: { defaultDepositPercent: values.defaultDepositPercent === '' ? null : Number(values.defaultDepositPercent), defaultEstimatedDelay: values.defaultEstimatedDelay } } })}</SettingsPanel>
    <SettingsPanel title="Numérotation" description="Le préfixe est appliqué aux nouveaux devis. La séquence existante est gérée automatiquement afin d’éviter les doublons." status="optional"><fieldset disabled={!canEdit} className="max-w-md"><label className="text-sm font-medium text-slate-700">Préfixe des devis<input className={field} value={values.devisPrefixe} onChange={e => update('devisPrefixe', e.target.value.toUpperCase())} maxLength={12} /></label></fieldset>{action('numbering', 'Enregistrer le préfixe', { devisPrefixe: values.devisPrefixe })}</SettingsPanel>
    <SettingsPanel title="Contenu des documents" description="Ces textes sont repris dans vos devis et leur PDF. Les valeurs d’un devis restent modifiables dossier par dossier." status="optional"><fieldset disabled={!canEdit} className="space-y-4"><label className="block text-sm font-medium text-slate-700">Conditions de paiement<textarea className={field} rows={3} value={values.devisConditionsPaiement} onChange={e => update('devisConditionsPaiement', e.target.value)} /></label><label className="block text-sm font-medium text-slate-700">Mentions de bas de page<textarea className={field} rows={4} value={values.devisMentionLegale} onChange={e => update('devisMentionLegale', e.target.value)} /></label></fieldset>{action('content', 'Enregistrer le contenu', { devisConditionsPaiement: values.devisConditionsPaiement, devisMentionLegale: values.devisMentionLegale })}</SettingsPanel>
    <SettingsPanel title="Informations héritées de l’entreprise" description="Ces éléments sont déjà repris dans les documents et restent gérés à un seul endroit." status="complete"><div className="grid gap-3 sm:grid-cols-2"><p className="rounded-lg bg-slate-50 p-3 text-sm text-slate-700"><strong>Logo et identité visuelle</strong><br />Configurés dans Entreprise &gt; Apparence.</p><p className="rounded-lg bg-slate-50 p-3 text-sm text-slate-700"><strong>Coordonnées et informations légales</strong><br />Configurées dans Entreprise.</p></div><Link href="/parametres/entreprise" className="mt-4 inline-flex text-sm font-medium text-emerald-700">Gérer les informations de l’entreprise</Link></SettingsPanel>
  </div>
}
