'use client'

import Link from 'next/link'
import { Activity, AlertTriangle, ArrowRight, CheckCircle2, ChevronRight, CircleAlert, Clock3, RefreshCw, ShieldCheck, Sparkles, TrendingUp, UserRoundCheck } from 'lucide-react'
import { useShellContext } from '@/src/components/workspace/shell/ShellContextProvider'
import type { TrackingBrief, TrackingEvidenceLevel, TrackingMovement, TrackingPipelineStage, TrackingProjectRow, TrackingSlowdown } from './tracking-contract'

type Props = { brief: TrackingBrief | null; loadState: 'loading' | 'ready' | 'error'; onRefresh: () => Promise<void> }

const stageTone: Record<TrackingPipelineStage['key'], { card: string; dot: string; badge: string }> = {
  new: { card: 'border-blue-100 bg-blue-50/40', dot: 'bg-blue-500', badge: 'bg-blue-50 text-blue-700' },
  qualification: { card: 'border-emerald-100 bg-emerald-50/40', dot: 'bg-emerald-500', badge: 'bg-emerald-50 text-emerald-700' },
  quote_to_prepare: { card: 'border-amber-100 bg-amber-50/40', dot: 'bg-amber-500', badge: 'bg-amber-50 text-amber-700' },
  quote_sent: { card: 'border-orange-100 bg-orange-50/40', dot: 'bg-orange-500', badge: 'bg-orange-50 text-orange-700' },
  waiting_client: { card: 'border-violet-100 bg-violet-50/40', dot: 'bg-violet-500', badge: 'bg-violet-50 text-violet-700' },
  won: { card: 'border-emerald-100 bg-emerald-50/40', dot: 'bg-emerald-600', badge: 'bg-emerald-50 text-emerald-700' },
}

const evidenceLabel: Record<TrackingEvidenceLevel, string> = { strong: 'Preuve solide', moderate: 'Lecture prudente', weak: 'Preuve limitée' }
const formatAmount = (value: number) => new Intl.NumberFormat('fr-FR', { style: 'currency', currency: 'EUR', maximumFractionDigits: 0 }).format(value)

function MovementRow({ item }: { item: TrackingMovement }) {
  const icon = item.tone === 'positive' ? <CheckCircle2 className="size-4" /> : item.tone === 'attention' ? <CircleAlert className="size-4" /> : <Activity className="size-4" />
  const colour = item.tone === 'positive' ? 'bg-emerald-50 text-emerald-700' : item.tone === 'attention' ? 'bg-amber-50 text-amber-700' : 'bg-blue-50 text-blue-700'
  return <Link href={`/dashboard-v2/projet/${item.projectId}`} className="flex min-w-0 items-center gap-3 py-2.5 transition-colors hover:bg-slate-50"><span className={`grid size-8 shrink-0 place-items-center rounded-full ${colour}`}>{icon}</span><span className="min-w-0 flex-1"><span className="block truncate text-xs font-semibold text-[#0b2232]">{item.clientLabel} <span className="font-normal text-slate-400">·</span> {item.title}</span><span className="block truncate text-[11px] text-slate-500">{item.description}</span></span><span className="hidden rounded-full bg-slate-100 px-2 py-1 text-[10px] font-semibold text-slate-600 lg:inline-flex">{item.stageLabel}</span><span className="shrink-0 text-[11px] text-slate-500">{item.timeLabel}</span></Link>
}

function SlowdownRow({ item }: { item: TrackingSlowdown }) {
  return <Link href={item.href} className="flex min-w-0 items-center gap-3 py-2.5 transition-colors hover:bg-slate-50"><span className="grid size-8 shrink-0 place-items-center rounded-full bg-red-50 text-red-600"><CircleAlert className="size-4" /></span><span className="min-w-0 flex-1"><span className="block truncate text-xs font-semibold text-[#0b2232]">{item.clientLabel} <span className="font-normal text-slate-400">·</span> {item.title}</span><span className="block truncate text-[11px] text-slate-500">{item.reason}</span></span><span className="hidden text-[10px] font-semibold text-slate-500 lg:inline">{evidenceLabel[item.evidenceLevel]}</span><span className="shrink-0 rounded-full bg-red-50 px-2 py-1 text-[10px] font-semibold text-red-600">{item.stalledForDays} j</span><ChevronRight className="size-4 shrink-0 text-slate-400" /></Link>
}

function Progress({ row }: { row: TrackingProjectRow }) {
  const tone = stageTone[row.stage]
  return <div className="flex min-w-[130px] items-center gap-1.5">{Array.from({ length: 6 }, (_, index) => <span key={index} className={`h-1.5 flex-1 rounded-full ${index < row.progress ? tone.dot : 'bg-slate-200'} ${index === row.progress - 1 ? 'ring-2 ring-offset-1 ring-slate-200' : ''}`} />)}<span className="ml-1 text-[10px] font-semibold text-slate-500">{row.progress}/6</span></div>
}

function ProjectTable({ rows }: { rows: TrackingProjectRow[] }) {
  if (!rows.length) return null
  return <section><p className="mb-2 text-[10px] font-bold uppercase tracking-[0.14em] text-slate-600">Tous vos dossiers en cours</p><div className="overflow-hidden rounded-[18px] border border-slate-200/80 bg-white shadow-[0_2px_10px_rgba(15,34,50,0.03)]"><div className="hidden overflow-x-auto lg:block"><table className="w-full min-w-[850px] text-left"><thead className="border-b border-slate-100 bg-slate-50/70 text-[10px] font-bold uppercase tracking-[0.08em] text-slate-500"><tr><th className="px-4 py-3">Dossier</th><th className="px-3 py-3">Client</th><th className="px-3 py-3">Étape actuelle</th><th className="px-3 py-3">Progression</th><th className="px-3 py-3">Dernière activité</th><th className="px-3 py-3">Prochain pas</th><th className="px-3 py-3" /></tr></thead><tbody className="divide-y divide-slate-100">{rows.map((row) => <tr key={row.id} className="text-xs"><td className="max-w-[190px] truncate px-4 py-3 font-semibold text-[#0b2232]">{row.title}</td><td className="max-w-[150px] truncate px-3 py-3 text-slate-600">{row.clientLabel}</td><td className="px-3 py-3"><span className={`rounded-full px-2 py-1 text-[10px] font-semibold ${stageTone[row.stage].badge}`}>{row.stageLabel}</span></td><td className="px-3 py-3"><Progress row={row} /></td><td className={`px-3 py-3 ${row.lastActivity.tone === 'attention' ? 'text-red-600' : row.lastActivity.tone === 'positive' ? 'text-emerald-700' : 'text-slate-600'}`}><span className="block font-semibold">{row.lastActivity.ageLabel}</span><span className="block max-w-[160px] truncate text-[10px]">{row.lastActivity.label}</span></td><td className="px-3 py-3"><Link href={row.nextStep.href} className="inline-flex items-center gap-1 font-semibold text-emerald-700 hover:text-emerald-800">{row.nextStep.label}<ArrowRight className="size-3.5" /></Link></td><td className="px-3 py-3"><Link aria-label={`Ouvrir ${row.title}`} href={`/dashboard-v2/projet/${row.id}`} className="text-slate-400 hover:text-emerald-700"><ChevronRight className="size-4" /></Link></td></tr>)}</tbody></table></div><div className="divide-y divide-slate-100 lg:hidden">{rows.map((row) => <Link key={row.id} href={`/dashboard-v2/projet/${row.id}`} className="block px-4 py-3"><div className="flex justify-between gap-3"><span className="min-w-0"><span className="block truncate text-sm font-semibold text-[#0b2232]">{row.title}</span><span className="block truncate text-xs text-slate-500">{row.clientLabel}</span></span><span className={`shrink-0 rounded-full px-2 py-1 text-[10px] font-semibold ${stageTone[row.stage].badge}`}>{row.stageLabel}</span></div><div className="mt-3 flex items-center justify-between gap-3"><Progress row={row} /><span className="text-[11px] font-semibold text-emerald-700">{row.nextStep.label}</span></div></Link>)}</div></div></section>
}

export default function TrackingWorkspace({ brief, loadState, onRefresh }: Props) {
  const { openCollaborator } = useShellContext()
  if (loadState === 'loading' || !brief && loadState !== 'error') return <div className="w-full space-y-4 pb-5" aria-busy="true"><div className="h-32 animate-pulse rounded-2xl bg-slate-200" /><div className="h-24 animate-pulse rounded-2xl bg-slate-200" /><div className="h-72 animate-pulse rounded-2xl bg-slate-200" /></div>
  if (!brief) return <div className="w-full rounded-2xl border border-slate-200 bg-white p-6"><CircleAlert className="size-5 text-amber-600" /><h1 className="mt-3 text-xl font-semibold text-[#0b2232]">Le suivi commercial est momentanément indisponible.</h1><p className="mt-2 text-sm text-slate-600">Vos dossiers ne sont pas modifiés. Réessayez pour actualiser l’analyse.</p><button type="button" onClick={() => void onRefresh()} className="mt-5 inline-flex min-h-10 items-center gap-2 rounded-lg bg-emerald-500 px-3 py-2 text-sm font-bold text-emerald-950"><RefreshCw className="size-4" />Réessayer</button></div>
  const workspace = brief.workspace
  if (!workspace) return <div className="w-full rounded-2xl border border-amber-200 bg-amber-50 px-5 py-4 text-sm text-amber-950">Le suivi commercial est en cours d’actualisation. Réessayez dans quelques instants.</div>
  const insufficient = brief.dataQuality.level === 'insufficient'
  const completedStages = workspace.progressedThroughQuoteCount
  return <div className="w-full max-w-none space-y-3.5 pb-4">
    <section className={`relative overflow-hidden rounded-[20px] border px-5 py-4 sm:px-6 ${insufficient ? 'border-amber-200 bg-amber-50' : 'border-slate-200/80 bg-[linear-gradient(108deg,#ffffff_0%,#fbfefd_62%,#ecfbf5_100%)]'}`}><div className="pointer-events-none absolute inset-y-0 right-0 hidden w-[31%] [background:radial-gradient(circle_at_72%_38%,rgba(110,231,183,.28),transparent_42%)] lg:block" /><div className="relative"><h1 className="text-[22px] font-semibold tracking-[-0.035em] text-[#0b2232]">Bonjour{workspace.firstName ? ` ${workspace.firstName}` : ''}.</h1><p className="mt-1 text-sm text-slate-600">{workspace.activeCount} dossier{workspace.activeCount > 1 ? 's' : ''} en cours.</p><div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-full bg-emerald-50 text-emerald-700"><TrendingUp className="size-4" /></span><span><b className="block text-sm text-[#0b2232]">{workspace.progressingCount} évoluent</b><span className="text-[11px] text-slate-500">Avancent avec les faits connus.</span></span></div><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-full bg-amber-50 text-amber-700"><Clock3 className="size-4" /></span><span><b className="block text-sm text-[#0b2232]">{workspace.slowingCount} ralentissent</b><span className="text-[11px] text-slate-500">Sans activité récente à vérifier.</span></span></div><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-full bg-red-50 text-red-600"><CircleAlert className="size-4" /></span><span><b className="block text-sm text-[#0b2232]">{workspace.decisionCount} nécessitent une décision</b><span className="text-[11px] text-slate-500">Une prochaine étape est attendue.</span></span></div></div>{brief.dataQuality.reservations.length > 0 && <p className="mt-3 flex gap-2 text-xs text-amber-900"><AlertTriangle className="size-4 shrink-0" />{brief.dataQuality.reservations.join(' ')}</p>}</div></section>

    {!insufficient && <><section><div className="mb-2 flex flex-wrap items-end justify-between gap-2"><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-slate-600">Où en sont vos opportunités ?</p>{workspace.quoteValueInProgress > 0 && <p className="text-xs text-slate-500">Valeur de devis en cours : <b className="text-[#0b2232]">{formatAmount(workspace.quoteValueInProgress)}</b></p>}</div><div className="flex gap-2 overflow-x-auto pb-1">{workspace.pipeline.map((stage, index) => <div key={stage.key} className="flex min-w-[148px] flex-1 items-center gap-2"><div className={`min-h-[82px] flex-1 rounded-[15px] border px-3 py-2.5 ${stageTone[stage.key].card}`}><span className="flex items-center gap-2 text-[11px] font-semibold text-slate-700"><span className={`size-2 rounded-full ${stageTone[stage.key].dot}`} />{stage.label}</span><b className="mt-2 block text-xl tracking-[-0.03em] text-[#0b2232]">{stage.count}</b>{stage.quoteAmount > 0 && <span className="mt-0.5 block text-[10px] text-slate-500">{formatAmount(stage.quoteAmount)} de devis</span>}</div>{index < workspace.pipeline.length - 1 && <ChevronRight className="size-4 shrink-0 text-slate-400" />}</div>)}</div><div className="mt-3 flex items-center gap-3 text-[11px] text-slate-600"><div className="h-1 flex-1 overflow-hidden rounded-full bg-slate-200"><div className="h-full rounded-full bg-emerald-500" style={{ width: workspace.activeCount ? `${Math.round((completedStages / workspace.activeCount) * 100)}%` : '0%' }} /></div><span><b>{completedStages}</b> dossier{completedStages > 1 ? 's' : ''} sur {workspace.activeCount} ont atteint l’étape devis ou au-delà.</span></div></section>

    <section className="grid gap-3 xl:grid-cols-[minmax(0,1fr)_minmax(0,0.78fr)_220px]"><div className="rounded-[18px] border border-slate-200/80 bg-white px-4 py-3 shadow-[0_2px_10px_rgba(15,34,50,0.03)]"><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-slate-600">Ce qui a bougé aujourd’hui</p>{workspace.movements.length ? <div className="mt-1 divide-y divide-slate-100">{workspace.movements.map((item) => <MovementRow key={item.id} item={item} />)}</div> : <p className="mt-3 text-xs text-slate-500">Aucun mouvement récent n’est enregistré dans les informations disponibles.</p>}</div><div className="rounded-[18px] border border-slate-200/80 bg-white px-4 py-3 shadow-[0_2px_10px_rgba(15,34,50,0.03)]"><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-slate-600">Dossiers qui ralentissent</p>{workspace.slowdowns.length ? <div className="mt-1 divide-y divide-slate-100">{workspace.slowdowns.map((item) => <SlowdownRow key={item.id} item={item} />)}</div> : <p className="mt-3 text-xs text-slate-500">Aucun ralentissement n’est identifié à partir des faits disponibles.</p>}</div><aside className="rounded-[18px] border border-slate-200/80 bg-white p-3 shadow-[0_2px_10px_rgba(15,34,50,0.03)]"><p className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.14em] text-slate-600"><Sparkles className="size-3.5 text-emerald-600" />L’analyse de Kadria</p>{workspace.slowdowns.length > 0 && <div className="mt-3 rounded-xl border border-red-100 bg-red-50/60 p-3"><p className="text-xs font-semibold text-[#0b2232]">Risque identifié</p><p className="mt-1 text-[11px] leading-4 text-slate-600">{workspace.slowdowns.length} dossier{workspace.slowdowns.length > 1 ? 's restent' : ' reste'} sans activité récente selon leur étape actuelle.</p><span className="mt-2 inline-flex text-[10px] font-semibold text-red-700">Preuve solide ou prudente selon le dossier</span></div>}<div className="mt-3 rounded-xl border border-emerald-100 bg-emerald-50/60 p-3"><p className="text-xs font-semibold text-[#0b2232]">Besoin d’un coup de pouce ?</p><p className="mt-1 text-[11px] leading-4 text-slate-600">Demandez à Kadria quelles actions auront le plus d’impact en ce moment.</p><button type="button" onClick={() => openCollaborator({ mode: 'actions' })} className="mt-3 inline-flex w-full items-center justify-center gap-1 rounded-lg bg-emerald-500 px-2 py-2 text-[11px] font-bold text-emerald-950 hover:bg-emerald-400"><UserRoundCheck className="size-3.5" />Demander à Kadria</button></div></aside></section>
    <ProjectTable rows={workspace.projects} /></>}
    {insufficient && <section className="rounded-2xl border border-amber-200 bg-amber-50 px-5 py-4 text-sm leading-6 text-amber-950"><ShieldCheck className="mr-2 inline size-4" />Les données disponibles ne permettent pas de confirmer une lecture commerciale complète.</section>}
  </div>
}
