'use client'

import Link from 'next/link'
import { ArrowRight, CircleAlert, RefreshCw, ShieldCheck, Target, TriangleAlert } from 'lucide-react'
import type { TrackingBrief, TrackingOpportunity } from './tracking-contract'

type Props = { brief: TrackingBrief | null; loadState: 'loading' | 'ready' | 'error'; onRefresh: () => Promise<void> }

const evidence = { strong: 'Faits confirmés', moderate: 'Signal à vérifier', weak: 'Lecture prudente' } as const

function OpportunityCard({ item }: { item: TrackingOpportunity }) {
  return <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[11px] font-bold uppercase tracking-[0.14em] text-emerald-700">{item.stage}</p><h2 className="mt-1 text-lg font-semibold text-[#0b2232]">{item.title}</h2><p className="mt-0.5 text-sm text-slate-500">{item.clientLabel}</p></div><span className="rounded-full border border-slate-200 bg-slate-50 px-2.5 py-1 text-xs font-semibold text-slate-600">{evidence[item.evidenceLevel]}</span></div><div className="mt-5 space-y-4 border-y border-slate-100 py-4 text-sm leading-6 text-slate-700"><div><p className="text-[10px] font-bold uppercase tracking-[0.12em] text-slate-500">Faits observés</p><p>{item.observedFacts.join(' ')}</p></div>{item.blockage && <div><p className="text-[10px] font-bold uppercase tracking-[0.12em] text-slate-500">Ce qui bloque</p><p>{item.blockage}</p></div>}{item.uncertainty && <p className="text-xs text-amber-800">À nuancer : {item.uncertainty}</p>}{item.missingInformation.length > 0 && <p className="text-xs text-amber-800">À compléter : {item.missingInformation.join(', ')}.</p>}</div><div className="mt-4 flex flex-wrap items-center justify-between gap-3"><p className="max-w-lg text-sm font-medium text-[#0b2232]">Je vous recommande : {item.recommendation}</p><Link href={item.destination.href} className="inline-flex min-h-10 items-center gap-2 rounded-lg bg-emerald-500 px-3 py-2 text-sm font-bold text-emerald-950 hover:bg-emerald-400 focus-visible:outline focus-visible:outline-2 focus-visible:outline-emerald-700 focus-visible:outline-offset-2">{item.destination.label}<ArrowRight className="size-4" /></Link></div></article>
}

export default function TrackingWorkspace({ brief, loadState, onRefresh }: Props) {
  if (loadState === 'loading' || !brief && loadState !== 'error') return <div className="mx-auto max-w-[960px] space-y-5 pb-5" aria-busy="true"><div className="h-36 animate-pulse rounded-2xl bg-slate-200" /><div className="h-64 animate-pulse rounded-2xl bg-slate-200" /></div>
  if (!brief) return <div className="mx-auto max-w-[760px] rounded-2xl border border-slate-200 bg-white p-6"><CircleAlert className="size-5 text-amber-600" /><h1 className="mt-3 text-xl font-semibold text-[#0b2232]">Le suivi commercial est momentanément indisponible.</h1><p className="mt-2 text-sm text-slate-600">Vos dossiers ne sont pas modifiés. Réessayez pour actualiser l’analyse.</p><button type="button" onClick={() => void onRefresh()} className="mt-5 inline-flex min-h-10 items-center gap-2 rounded-lg bg-emerald-500 px-3 py-2 text-sm font-bold text-emerald-950"><RefreshCw className="size-4" />Réessayer</button></div>
  const insufficient = brief.dataQuality.level === 'insufficient'
  return <div className="mx-auto max-w-[960px] space-y-6 pb-5"><section className={`rounded-2xl border px-6 py-6 ${insufficient ? 'border-amber-200 bg-amber-50' : 'border-slate-200 bg-white'}`}><p className="flex items-center gap-2 text-[11px] font-bold uppercase tracking-[0.14em] text-emerald-700"><Target className="size-4" />Suivi commercial</p><h1 className="mt-2 text-2xl font-semibold tracking-tight text-[#0b2232]">{insufficient ? 'Les informations disponibles ne suffisent pas à confirmer le suivi.' : brief.opportunities.length ? 'Les opportunités à faire progresser.' : 'Aucune opportunité ne semble stagner.'}</h1><p className="mt-3 text-sm leading-6 text-slate-600">{insufficient ? 'Aucune conclusion calme n’est tirée tant que la collecte reste limitée.' : 'Cette lecture se concentre sur les devis, rappels et dossiers qui ont besoin d’une prochaine étape.'}</p>{brief.dataQuality.reservations.length > 0 && <p className="mt-3 flex gap-2 text-xs text-amber-900"><TriangleAlert className="size-4 shrink-0" />{brief.dataQuality.reservations.join(' ')}</p>}</section>{!insufficient && brief.opportunities.length > 0 && <section><p className="text-xs font-bold uppercase tracking-[0.14em] text-slate-600">Opportunités à faire progresser</p><div className="mt-3 space-y-3">{brief.opportunities.map((item) => <OpportunityCard key={item.id} item={item} />)}</div></section>}{!insufficient && brief.opportunities.length === 0 && <section className="rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><div className="flex gap-3"><ShieldCheck className="size-5 text-emerald-700" /><p className="text-sm leading-6 text-emerald-950">Aucun devis sans réponse, rappel manquant ou dossier qui semble stagner n’est identifié à partir des données disponibles.</p></div></section>}</div>
}
