'use client'

import { useCallback, useEffect, useMemo, useState } from 'react'
import type { TenantRole } from '@/src/lib/team/types'

export type AssistantSettings = { artisanId: string; companyName: string; logoUrl: string; plan: string; assistantAvatarType: string; assistantAvatarUrl: string; welcomeName: string; welcomeMessage: string; primaryColor: string; secondaryColor: string; widgetColorMode: 'sobriety' | 'immersive' | 'premium_dark'; whiteLabelEnabled: boolean; widgetBrandName: string; widgetBrandLogoUrl: string }
const EMPTY: AssistantSettings = { artisanId: '', companyName: '', logoUrl: '', plan: 'essentiel', assistantAvatarType: 'kadria_default', assistantAvatarUrl: '', welcomeName: '', welcomeMessage: '', primaryColor: '#22c55e', secondaryColor: '#18181b', widgetColorMode: 'sobriety', whiteLabelEnabled: false, widgetBrandName: '', widgetBrandLogoUrl: '' }
const text = (v: unknown) => typeof v === 'string' ? v : ''

/** Contrôleur isolé du widget; aucune clé Vapi/OVH n'est exposée côté client. */
export function useAssistantSettingsData() {
  const [role, setRole] = useState<TenantRole | null>(null); const [values, setValues] = useState<AssistantSettings>(EMPTY); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState<Record<string, boolean>>({}); const [messages, setMessages] = useState<Record<string, string>>({}); const [uploading, setUploading] = useState<string | null>(null)
  const load = useCallback(async () => { setLoading(true); try { const [configRes, teamRes] = await Promise.all([fetch('/api/artisan/config'), fetch('/api/team')]); const [configData, teamData] = await Promise.all([configRes.json(), teamRes.json().catch(() => null)]); if (!configData?.success || !configData.config) throw new Error('Kadria n’a pas pu charger les assistants.'); const c = configData.config; setValues({ artisanId: text(c.artisanId) || text(c.id), companyName: text(c.companyName), logoUrl: text(c.logoUrl), plan: text(c.plan) || 'essentiel', assistantAvatarType: text(c.assistantAvatarType) || 'kadria_default', assistantAvatarUrl: text(c.assistantAvatarUrl), welcomeName: text(c.welcomeName), welcomeMessage: text(c.welcomeMessage), primaryColor: text(c.primaryColor) || '#22c55e', secondaryColor: text(c.secondaryColor) || '#18181b', widgetColorMode: ['sobriety', 'immersive', 'premium_dark'].includes(c.widgetColorMode) ? c.widgetColorMode : 'sobriety', whiteLabelEnabled: Boolean(c.whiteLabelEnabled), widgetBrandName: text(c.widgetBrandName), widgetBrandLogoUrl: text(c.widgetBrandLogoUrl) }); if (teamData?.membership?.role) setRole(teamData.membership.role as TenantRole) } catch (error) { setMessages({ load: error instanceof Error ? error.message : 'Erreur de chargement.' }) } finally { setLoading(false) } }, [])
  useEffect(() => { const timer = window.setTimeout(() => { void load() }, 0); return () => window.clearTimeout(timer) }, [load])
  const save = async (domain: string, patch: Partial<AssistantSettings>) => { setSaving(s => ({ ...s, [domain]: true })); setMessages(m => ({ ...m, [domain]: '' })); try { const response = await fetch('/api/artisan/config', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(patch) }); const data = await response.json(); if (!data?.success) throw new Error(data?.error || 'Enregistrement impossible.'); setValues(current => ({ ...current, ...patch })); setMessages(m => ({ ...m, [domain]: 'Enregistré' })) } catch (error) { setMessages(m => ({ ...m, [domain]: error instanceof Error ? error.message : 'Enregistrement impossible.' })) } finally { setSaving(s => ({ ...s, [domain]: false })) } }
  const upload = async (target: 'assistant_avatar' | 'white_label_logo', file: File) => { setUploading(target); setMessages(m => ({ ...m, upload: '' })); try { const form = new FormData(); form.append('file', file); form.append('target', target); const response = await fetch('/api/uploads/artisan-branding', { method: 'POST', body: form }); const data = await response.json(); if (!data?.success || !data.url) throw new Error(data?.error || 'Import impossible.'); const patch = target === 'assistant_avatar' ? { assistantAvatarType: 'custom_upload', assistantAvatarUrl: data.url as string } : { widgetBrandLogoUrl: data.url as string }; setValues(current => ({ ...current, ...patch })); setMessages(m => ({ ...m, upload: 'Image importée — enregistrez vos modifications.' })) } catch (error) { setMessages(m => ({ ...m, upload: error instanceof Error ? error.message : 'Import impossible.' })) } finally { setUploading(null) } }
  const script = useMemo(() => values.artisanId ? `<script src="${process.env.NEXT_PUBLIC_APP_URL || 'https://kadria-beta.vercel.app'}/widget.js" data-artisan-id="${values.artisanId}"></script>` : '', [values.artisanId])
  return { role, values, setValues, loading, saving, messages, uploading, save, upload, script, reload: load }
}
