'use client'

import { useEffect, useState } from 'react'
import { hasPermission } from '@/src/lib/team/permission-matrix'
import type { TenantRole } from '@/src/lib/team/types'
import { ReadOnlyNotice } from '@/src/components/settings/ReadOnlyNotice'
import { SettingsPanel } from '@/src/components/settings/SettingsPanel'

type CatalogItem = { id: string; name: string; category: string | null; price_ht: number | null; unit: string | null; vat_rate: number | null; is_active: boolean }
const field = 'mt-1 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm text-slate-900 outline-none focus:border-emerald-500 focus:ring-2 focus:ring-emerald-100 disabled:bg-slate-50'
const blank = { name: '', category: '', priceHt: '', unit: 'u', vatRate: '20' }

export function CatalogSettingsView() {
  const [items, setItems] = useState<CatalogItem[]>([]); const [role, setRole] = useState<TenantRole | null>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState<string | null>(null); const [message, setMessage] = useState(''); const [draft, setDraft] = useState(blank); const [editing, setEditing] = useState<CatalogItem | null>(null)
  const canEdit = role !== null && hasPermission(role, 'business_settings.update')
  const load = async () => { setLoading(true); try { const [catalog, team] = await Promise.all([fetch('/api/artisan/service-catalog'), fetch('/api/team')]); const [catalogData, teamData] = await Promise.all([catalog.json(), team.json().catch(() => null)]); if (!catalogData.success) throw new Error(catalogData.error || 'Le catalogue est indisponible.'); setItems(catalogData.items || []); if (teamData?.membership?.role) setRole(teamData.membership.role as TenantRole); else setMessage('Les autorisations n’ont pas pu être vérifiées.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Le catalogue est indisponible.') } finally { setLoading(false) } }
  useEffect(() => { const timer = window.setTimeout(() => { void load() }, 0); return () => window.clearTimeout(timer) }, [])
  const request = async (key: string, url: string, method: string, body?: unknown) => { setSaving(key); setMessage(''); try { const result = await fetch(url, { method, headers: body ? { 'Content-Type': 'application/json' } : undefined, body: body ? JSON.stringify(body) : undefined }); const data = await result.json(); if (!data.success) throw new Error(data.error || 'Enregistrement impossible.'); await load(); setMessage('Enregistré.'); return true } catch (error) { setMessage(error instanceof Error ? error.message : 'Enregistrement impossible.'); return false } finally { setSaving(null) } }
  const create = async () => { if (!draft.name.trim()) return setMessage('Le nom de la prestation est requis.'); const ok = await request('create', '/api/artisan/service-catalog', 'POST', { name: draft.name, category: draft.category || null, priceHt: Number(draft.priceHt) || 0, unit: draft.unit || 'u', vatRate: Number(draft.vatRate) || 0 }); if (ok) setDraft(blank) }
  const update = async () => { if (!editing || !editing.name.trim()) return; const ok = await request(editing.id, `/api/artisan/service-catalog/${editing.id}`, 'PATCH', { name: editing.name, category: editing.category, priceHt: editing.price_ht, unit: editing.unit, vatRate: editing.vat_rate }); if (ok) setEditing(null) }
  if (loading) return <p role="status" className="rounded-xl border border-slate-200 bg-white p-5 text-sm text-slate-600">Chargement du catalogue…</p>
  return <div className="space-y-4">{!canEdit && <ReadOnlyNotice message={role ? 'Le catalogue est en lecture seule pour votre rôle.' : 'Les autorisations n’ont pas pu être vérifiées.'} />}
    <SettingsPanel title="Vos prestations" description="Les prestations actives sont proposées dans la création de devis." status={items.length ? 'complete' : 'incomplete'}><div className="grid gap-3 sm:grid-cols-3"><p className="rounded-lg bg-slate-50 p-3 text-sm text-slate-700"><strong>{items.length}</strong><br />prestations configurées</p><p className="rounded-lg bg-slate-50 p-3 text-sm text-slate-700"><strong>{items.filter(item => item.is_active).length}</strong><br />actives dans les devis</p><p className="rounded-lg bg-slate-50 p-3 text-sm text-slate-700"><strong>{items.filter(item => !item.is_active).length}</strong><br />inactives</p></div></SettingsPanel>
    <SettingsPanel title="Catalogue de prestations" description="Ajoutez, modifiez ou désactivez les éléments réutilisables dans vos futurs devis."><fieldset disabled={!canEdit} className="grid gap-3 md:grid-cols-5"><label className="text-sm font-medium text-slate-700 md:col-span-2">Nom<input className={field} value={draft.name} onChange={e => setDraft({ ...draft, name: e.target.value })} /></label><label className="text-sm font-medium text-slate-700">Prix HT<input className={field} type="number" min="0" value={draft.priceHt} onChange={e => setDraft({ ...draft, priceHt: e.target.value })} /></label><label className="text-sm font-medium text-slate-700">Unité<input className={field} value={draft.unit} onChange={e => setDraft({ ...draft, unit: e.target.value })} /></label><label className="text-sm font-medium text-slate-700">TVA<select className={field} value={draft.vatRate} onChange={e => setDraft({ ...draft, vatRate: e.target.value })}>{[0, 5.5, 10, 20].map(rate => <option key={rate}>{rate}</option>)}</select></label></fieldset>{canEdit && <button type="button" disabled={saving === 'create'} onClick={() => void create()} className="mt-4 rounded-lg bg-emerald-600 px-4 py-2 text-sm font-medium text-white disabled:opacity-60">{saving === 'create' ? 'Ajout…' : 'Ajouter une prestation'}</button>}
      <div className="mt-5 space-y-3">{items.map(item => <div key={item.id} className="rounded-lg border border-slate-200 p-4"><div className="flex flex-wrap items-start justify-between gap-3">{editing?.id === item.id ? <div className="grid flex-1 gap-3 sm:grid-cols-4"><input className={field} value={editing.name} onChange={e => setEditing({ ...editing, name: e.target.value })} /><input className={field} type="number" value={editing.price_ht ?? 0} onChange={e => setEditing({ ...editing, price_ht: Number(e.target.value) })} /><input className={field} value={editing.unit || ''} onChange={e => setEditing({ ...editing, unit: e.target.value })} /><select className={field} value={editing.vat_rate ?? 20} onChange={e => setEditing({ ...editing, vat_rate: Number(e.target.value) })}>{[0, 5.5, 10, 20].map(rate => <option key={rate}>{rate}</option>)}</select></div> : <div><p className="font-medium text-slate-900">{item.name}</p><p className="mt-1 text-sm text-slate-600">{(item.price_ht || 0).toLocaleString('fr-FR', { minimumFractionDigits: 2 })} € HT / {item.unit || 'u'} · TVA {item.vat_rate ?? 0}% · {item.is_active ? 'Active' : 'Inactive'}</p>{item.category && <p className="mt-1 text-xs text-slate-500">{item.category}</p>}</div>}<div className="flex flex-wrap gap-2">{editing?.id === item.id ? <><button type="button" onClick={() => void update()} disabled={saving === item.id} className="rounded-md bg-emerald-600 px-3 py-1.5 text-xs font-medium text-white">Enregistrer</button><button type="button" onClick={() => setEditing(null)} className="rounded-md border border-slate-300 px-3 py-1.5 text-xs">Annuler</button></> : <><button type="button" disabled={!canEdit} onClick={() => setEditing(item)} className="rounded-md border border-slate-300 px-3 py-1.5 text-xs disabled:opacity-60">Modifier</button><button type="button" disabled={!canEdit || saving === item.id} onClick={() => void request(item.id, `/api/artisan/service-catalog/${item.id}`, 'PATCH', { isActive: !item.is_active })} className="rounded-md border border-slate-300 px-3 py-1.5 text-xs disabled:opacity-60">{item.is_active ? 'Désactiver' : 'Activer'}</button><button type="button" disabled={!canEdit || saving === item.id} onClick={() => { if (window.confirm('Cette prestation ne sera plus disponible pour les futurs devis. Les devis existants resteront inchangés.')) void request(item.id, `/api/artisan/service-catalog/${item.id}`, 'DELETE') }} className="rounded-md border border-red-300 px-3 py-1.5 text-xs text-red-700 disabled:opacity-60">Supprimer</button></>}</div></div></div>)}</div>{message && <p role={message === 'Enregistré.' ? 'status' : 'alert'} className="mt-3 text-sm text-slate-700">{message}</p>}</SettingsPanel>
    <SettingsPanel title="Utilisation dans les devis" description="La désactivation retire une prestation du sélecteur des futurs devis, sans modifier les devis existants." status="optional"><p className="text-sm text-slate-600">Les lignes d’un devis existant sont conservées comme un instantané, même si la prestation est modifiée ou supprimée ensuite.</p></SettingsPanel>
  </div>
}
