import { ExternalLink, Route } from 'lucide-react';
import { formatAgendaDuration, type AgendaDaySummary } from './agenda-day-summary';

type Props = { summary: AgendaDaySummary };

export default function AgendaDayInsights({ summary }: Props) {
  if (!summary.routeStops || !summary.mapsUrl) return null;
  return <section aria-label="Itinéraire du jour"><article className="rounded-2xl border border-slate-200 bg-white p-4"><div className="flex flex-wrap items-center justify-between gap-3"><p className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.14em] text-slate-500"><Route className="size-4 text-violet-600" />Itinéraire du jour</p><a href={summary.mapsUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-xs font-semibold text-emerald-700 hover:text-emerald-800 focus-visible:outline focus-visible:outline-2 focus-visible:outline-emerald-500">Ouvrir dans Google Maps<ExternalLink className="size-3.5" /></a></div><ol className="mt-4 grid gap-3 sm:grid-flow-col sm:grid-cols-none sm:auto-cols-fr sm:items-start">{summary.routeStops.map((stop, index) => <li key={stop.id} className="relative min-w-0 border-l border-violet-200 pl-3 sm:border-l-0 sm:border-t sm:pl-0 sm:pt-3"><span className="absolute -left-1.5 top-0 grid size-3 place-items-center rounded-full bg-violet-600 text-[0px] sm:left-0 sm:-top-1.5">{index + 1}</span><p className="text-sm font-bold text-slate-900">{stop.time || 'Horaire à préciser'}</p><p className="mt-0.5 truncate text-xs font-semibold text-slate-700">{stop.label}</p><p className="mt-0.5 truncate text-xs text-slate-500">{stop.address}</p></li>)}</ol><p className="mt-4 text-xs font-medium text-slate-500">{summary.routeStops.length} étape{summary.routeStops.length > 1 ? 's' : ''}{summary.travelMinutes !== null ? ` · ${formatAgendaDuration(summary.travelMinutes)} de trajet planifié` : ''}</p></article></section>;
}
