import { CalendarClock, CheckCircle2, ExternalLink, MapPinned, Route, Sparkles } from 'lucide-react';
import type { ScheduleSituation } from '@/src/lib/calendar/schedule-situations';
import type { NormalizedCalendarEvent } from '@/src/lib/calendar/normalized-event';
import { formatAgendaDuration, type AgendaDaySummary } from './agenda-day-summary';
import NextAppointmentPanel from './NextAppointmentPanel';

type Props = {
  summary: AgendaDaySummary;
  situation: ScheduleSituation | null;
  nextAppointment: NormalizedCalendarEvent | null;
  onOpenProject: (event: NormalizedCalendarEvent) => void;
};

export default function AgendaDayInsights({ summary, situation, nextAppointment, onOpenProject }: Props) {
  const hasStats = summary.appointmentCount > 0;
  const showAdvice = !situation && hasStats;
  if (!hasStats && !summary.routeStops && summary.availableSlots === null && !nextAppointment) return null;

  return <section aria-label="Informations opérationnelles de la journée" className="grid items-start gap-4 md:grid-cols-2">
    {summary.routeStops && summary.mapsUrl ? <article className="rounded-2xl border border-slate-200 bg-white p-4 md:col-span-2"><div className="flex flex-wrap items-center justify-between gap-3"><p className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.14em] text-slate-500"><Route className="size-4 text-violet-600" />Itinéraire du jour</p><a href={summary.mapsUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-xs font-semibold text-emerald-700 hover:text-emerald-800 focus-visible:outline focus-visible:outline-2 focus-visible:outline-emerald-500">Ouvrir dans Maps<ExternalLink className="size-3.5" /></a></div><ol className="mt-4 grid gap-3 sm:grid-flow-col sm:grid-cols-none sm:auto-cols-fr sm:items-start">{summary.routeStops.map((stop, index) => <li key={stop.id} className="relative min-w-0 border-l border-violet-200 pl-3 sm:border-l-0 sm:border-t sm:pl-0 sm:pt-3"><span className="absolute -left-1.5 top-0 grid size-3 place-items-center rounded-full bg-violet-600 text-[0px] sm:left-0 sm:-top-1.5">{index + 1}</span><p className="text-sm font-bold text-slate-900">{stop.time || 'Horaire à préciser'}</p><p className="mt-0.5 truncate text-xs font-semibold text-slate-700">{stop.label}</p><p className="mt-0.5 truncate text-xs text-slate-500">{stop.address}</p></li>)}</ol><p className="mt-4 text-xs font-medium text-slate-500">{summary.routeStops.length} étape{summary.routeStops.length > 1 ? 's' : ''}{summary.travelMinutes !== null ? ` · ${formatAgendaDuration(summary.travelMinutes)} de trajet planifié` : ''}</p></article> : null}
    {hasStats ? <article className="rounded-2xl border border-slate-200 bg-white p-4"><p className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.14em] text-slate-500"><CalendarClock className="size-4 text-emerald-600" />Votre journée en chiffres</p><dl className="mt-3 grid grid-cols-2 gap-px overflow-hidden rounded-xl border border-slate-100 bg-slate-100 text-sm">{[{ label: 'Rendez-vous', value: String(summary.appointmentCount) }, ...(summary.plannedMinutes !== null ? [{ label: 'Temps d’intervention', value: formatAgendaDuration(summary.plannedMinutes) }] : []), ...(summary.travelMinutes !== null ? [{ label: 'Temps de trajet', value: formatAgendaDuration(summary.travelMinutes) }] : []), ...(summary.availableMinutes !== null ? [{ label: 'Disponibilité restante', value: formatAgendaDuration(summary.availableMinutes) }] : []), ...(summary.estimatedEnd ? [{ label: 'Fin estimée', value: summary.estimatedEnd }] : [])].map((metric) => <div key={metric.label} className="bg-white px-3 py-2.5"><dt className="text-[10px] font-medium text-slate-500">{metric.label}</dt><dd className="mt-1 font-bold text-slate-950">{metric.value}</dd></div>)}</dl>{summary.incompleteDurations ? <p className="mt-3 text-xs leading-5 text-amber-800">Certaines durées sont incomplètes : les disponibilités et la fin de journée ne sont pas calculées.</p> : null}</article> : null}
    {summary.availableSlots !== null ? <article className="rounded-2xl border border-slate-200 bg-white p-4"><p className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.14em] text-slate-500"><MapPinned className="size-4 text-blue-600" />Créneaux disponibles</p>{summary.availableSlots.length ? <div className="mt-3 space-y-2">{summary.availableSlots.map((slot) => <div key={`${slot.start}-${slot.end}`} className="rounded-xl border border-slate-100 bg-slate-50 px-3 py-2"><p className="text-sm font-semibold text-slate-900">{slot.start}–{slot.end}</p><p className="mt-0.5 text-xs text-slate-600">{formatAgendaDuration(slot.minutes)} disponibles</p></div>)}</div> : <p className="mt-3 text-sm leading-6 text-slate-600">Aucun créneau significatif aujourd’hui.</p>}<p className="mt-3 text-right text-xs font-semibold text-emerald-700">Voir tous les créneaux</p></article> : null}
    <NextAppointmentPanel event={nextAppointment} onOpenProject={onOpenProject} />
    {showAdvice ? <article className="rounded-2xl border border-slate-200 bg-white p-4"><p className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.14em] text-slate-500"><Sparkles className="size-4 text-amber-600" />Conseil Kadria</p><div className="mt-3 flex items-start gap-2.5"><CheckCircle2 className="mt-0.5 size-4 shrink-0 text-emerald-600" /><p className="text-sm leading-5 text-slate-700">Votre journée ne présente pas de point de vigilance détecté.</p></div></article> : null}
  </section>;
}
