'use client';

import { BriefcaseBusiness, FilePenLine, MapPin, Phone, X } from 'lucide-react';
import { useEffect, useRef } from 'react';
import type { NormalizedCalendarEvent } from '@/src/lib/calendar/normalized-event';

type Props = { event: NormalizedCalendarEvent; onClose: () => void; onBrief: () => void; onEdit: () => void; onOpenProject: () => void };

export default function AppointmentContextMenu({ event, onClose, onBrief, onEdit, onOpenProject }: Props) {
  const closeRef = useRef<HTMLButtonElement>(null);
  useEffect(() => { closeRef.current?.focus(); const onKeyDown = (item: KeyboardEvent) => { if (item.key === 'Escape') onClose(); }; window.addEventListener('keydown', onKeyDown); return () => window.removeEventListener('keydown', onKeyDown); }, [onClose]);
  const address = event.address || event.location;
  const mapsUrl = address ? `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(address)}` : null;
  return <div className="fixed inset-0 z-[70] flex items-end justify-center bg-slate-950/35 p-4 sm:items-center" onMouseDown={onClose}><div role="dialog" aria-modal="true" aria-labelledby="appointment-context-title" onMouseDown={(item) => item.stopPropagation()} className="w-full max-w-sm overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-[0_24px_80px_rgba(15,23,42,0.28)]"><div className="flex items-start justify-between gap-3 border-b border-slate-100 px-5 py-4"><div className="min-w-0"><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-emerald-700">Rendez-vous</p><h2 id="appointment-context-title" className="mt-1 truncate text-base font-bold text-slate-950">{event.title}</h2><p className="mt-0.5 truncate text-xs text-slate-500">{event.clientName || event.projectTitle || 'Rendez-vous'}</p></div><button ref={closeRef} type="button" onClick={onClose} aria-label="Fermer le menu du rendez-vous" className="grid size-8 place-items-center rounded-lg text-slate-500 hover:bg-slate-100"><X className="size-4" /></button></div><div className="p-2"><button type="button" onClick={onBrief} className="flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm font-bold text-emerald-800 hover:bg-emerald-50"><BriefcaseBusiness className="size-4" />Brief Kadria</button><div className="my-1 border-t border-slate-100" /><button type="button" onClick={onEdit} className="flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm font-semibold text-slate-700 hover:bg-slate-50"><FilePenLine className="size-4 text-slate-400" />Modifier le rendez-vous</button>{event.projectId ? <button type="button" onClick={onOpenProject} className="flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm font-semibold text-slate-700 hover:bg-slate-50"><BriefcaseBusiness className="size-4 text-slate-400" />Ouvrir le dossier</button> : null}{event.clientPhone ? <a href={`tel:${event.clientPhone}`} className="flex w-full items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold text-slate-700 hover:bg-slate-50"><Phone className="size-4 text-slate-400" />Téléphoner</a> : null}{mapsUrl ? <a href={mapsUrl} target="_blank" rel="noreferrer" className="flex w-full items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold text-slate-700 hover:bg-slate-50"><MapPin className="size-4 text-slate-400" />Google Maps</a> : null}</div></div></div>;
}
